In [2]:
print("Hello World")

Hello World

In [2]:
import json

In [ ]:
import pandas as pd

In [7]:
import streamlit as st
st.write("Hello World")

2026-07-26 20:48:24.152 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-26 20:48:24.591
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run e:\vscode\.venv\lib\site-packages\ipykernel_launcher.py [ARGUMENTS]
2026-07-26 20:48:24.591 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-26 20:48:24.591 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

In [13]:
import os
os.getcwd()

'e:\\vscode'

In [14]:
import os
os.listdir()

['.venv',
 'agents_cleaned.json',
 'app.py',
 'buyers_cleaned.json',
 'employee.db',
 'listings_final_expanded.json',
 'Project_1.ipynb',
 'Project_1.py',
 'property_attributes_final_expanded.json',
 'sales_cleaned.csv']

In [21]:
import json

In [22]:
import os
print(os.getcwd())
print(os.listdir())

e:\vscode
['.venv', 'agents_cleaned.json', 'app.py', 'buyers_cleaned.json', 'employee.db', 'listings_final_expanded.json', 'Project_1.ipynb', 'Project_1.py', 'property_attributes_final_expanded.json', 'sales_cleaned.csv']

In [24]:
import json
import pandas as pd

In [26]:
listings_df = pd.read_json("listings_final_expanded.json")

In [27]:
property_df = pd.read_json("property_attributes_final_expanded.json")

In [36]:
import pandas as pd
df = pd.read_json("listings_final_expanded.json")
df.to_csv("listings_final_expanded.csv"),
print("CSV file created successfully.")

CSV file created successfully.

In [32]:
import pandas as pd
df = pd.read_json("property_attributes_final_expanded.json")
df.to_csv("property_attributes_final_expanded.csv", index=False)
print("CSV file created successfully.")

CSV file created successfully.

In [34]:
import pandas as pd
df = pd.read_json("agents_cleaned.json")
df.to_csv("agents_cleaned.csv", index=False)
print("csv file created successfully.")

csv file created successfully.

In [35]:
import pandas as pd
df = pd.read_json("buyers_cleaned.json")
df.to_csv("buyers_cleaned.csv", index=False)
print("csv file created successfully.")

csv file created successfully.

In [37]:
listings_df = pd.read_csv("listings_final_expanded.csv")

In [42]:
listings_df = pd.read_csv("listings_final_expanded.csv")
property_df = pd.read_csv("property_attributes_final_expanded.csv")
agents_df = pd.read_csv("agents_cleaned.csv")
sales_df = pd.read_csv("sales_cleaned.csv")
buyers_df = pd.read_csv("buyers_cleaned.csv")
print("All csv files loaded successfully.")

All csv files loaded successfully.

In [1]:
import json
import pandas as pd

with open("listings_final_expanded.json", "r") as file:
    data = json.load(file)    #data is now a list of dictionaries

In [2]:
data

[{'Listing_ID': 'L00001',
  'City': 'New York',
  'Property_Type': 'Apartment',
  'Price': 1655144.006669635,
  'Sqft': 2753.009121237,
  'Date_Listed': '2023-05-06',
  'Agent_ID': 'A0015',
  'Latitude': 33.9652080059,
  'Longitude': -69.8615892795},
 {'Listing_ID': 'L00002',
  'City': 'Los Angeles',
  'Property_Type': 'Apartment',
  'Price': 1519141.0026169808,
  'Sqft': 4966.9881928135,
  'Date_Listed': '2023-02-14',
  'Agent_ID': 'A0038',
  'Latitude': 42.5478920594,
  'Longitude': -90.2778602519},
 {'Listing_ID': 'L00003',
  'City': 'Houston',
  'Property_Type': 'Apartment',
  'Price': 162488.9975420714,
  'Sqft': 1267.0039591344,
  'Date_Listed': '2023-04-22',
  'Agent_ID': 'A0015',
  'Latitude': 28.7323266553,
  'Longitude': -115.9529818783},
 {'Listing_ID': 'L00004',
  'City': 'Phoenix',
  'Property_Type': 'Apartment',
  'Price': 1277015.9840670894,
  'Sqft': 2128.0144287921,
  'Date_Listed': '2024-01-02',
  'Agent_ID': 'A0042',
  'Latitude': 26.4039382837,
  'Longitude': -74.7714904573},
 {'Listing_ID': 'L00005',
  'City': 'Phoenix',
  'Property_Type': 'Townhouse',
  'Price': 562297.0068077513,
  'Sqft': 4178.9974210875,
  'Date_Listed': '2023-10-29',
  'Agent_ID': 'A0018',
  'Latitude': 39.4252516293,
  'Longitude': -83.9178782667},
 {'Listing_ID': 'L00006',
  'City': 'New York',
  'Property_Type': 'House',
  'Price': 1564104.0078713011,
  'Sqft': 3961.992615551,
  'Date_Listed': '2023-06-24',
  'Agent_ID': 'A0018',
  'Latitude': 25.4877926032,
  'Longitude': -68.7571139192},
 {'Listing_ID': 'L00007',
  'City': 'Los Angeles',
  'Property_Type': 'House',
  'Price': 1701163.003815294,
  'Sqft': 3257.0150616858,
  'Date_Listed': '2023-02-22',
  'Agent_ID': 'A0006',
  'Latitude': 44.9691124588,
  'Longitude': -112.6784942679},
 {'Listing_ID': 'L00008',
  'City': 'Houston',
  'Property_Type': 'Apartment',
  'Price': 852834.0147462517,
  'Sqft': 3316.9937214813,
  'Date_Listed': '2023-11-06',
  'Agent_ID': 'A0017',
  'Latitude': 29.3549128014,
  'Longitude': -114.3646813823},
 {'Listing_ID': 'L00009',
  'City': 'New York',
  'Property_Type': 'Townhouse',
  'Price': 1224550.9990439962,
  'Sqft': 1522.0077799342,
  'Date_Listed': '2024-05-13',
  'Agent_ID': 'A0025',
  'Latitude': 32.3025694404,
  'Longitude': -94.5569819185},
 {'Listing_ID': 'L00010',
  'City': 'New York',
  'Property_Type': 'Condo',
  'Price': 1839386.9924549507,
  'Sqft': 3462.0226393851,
  'Date_Listed': '2023-10-23',
  'Agent_ID': 'A0013',
  'Latitude': 35.3703968658,
  'Longitude': -108.1193181126},
 {'Listing_ID': 'L00011',
  'City': 'New York',
  'Property_Type': 'Apartment',
  'Price': 1486768.99430001,
  'Sqft': 2366.0004685872,
  'Date_Listed': '2024-01-31',
  'Agent_ID': 'A0019',
  'Latitude': 39.6667837428,
  'Longitude': -116.9028968424},
 {'Listing_ID': 'L00012',
  'City': 'New York',
  'Property_Type': 'House',
  'Price': 1917147.0045034816,
  'Sqft': 1326.9966016133,
  'Date_Listed': '2023-07-14',
  'Agent_ID': 'A0018',
  'Latitude': 32.0067048962,
  'Longitude': -103.728939014},
 {'Listing_ID': 'L00013',
  'City': 'Houston',
  'Property_Type': 'Condo',
  'Price': 441109.9971346703,
  'Sqft': 3532.0009552261,
  'Date_Listed': '2023-07-01',
  'Agent_ID': 'A0014',
  'Latitude': 35.9403141234,
  'Longitude': -79.4629622952},
 {'Listing_ID': 'L00014',
  'City': 'Chicago',
  'Property_Type': 'Apartment',
  'Price': 1377440.009039592,
  'Sqft': 1900.9981292033,
  'Date_Listed': '2023-10-01',
  'Agent_ID': 'A0047',
  'Latitude': 29.7726767961,
  'Longitude': -95.1627789955},
 {'Listing_ID': 'L00015',
  'City': 'Los Angeles',
  'Property_Type': 'House',
  'Price': 1069428.9949294312,
  'Sqft': 3607.9958386703,
  'Date_Listed': '2023-05-19',
  'Agent_ID': 'A0041',
  'Latitude': 39.2149977097,
  'Longitude': -122.2951451057},
 {'Listing_ID': 'L00016',
  'City': 'Phoenix',
  'Property_Type': 'House',
  'Price': 1535739.9878467089,
  'Sqft': 3155.9855295615,
  'Date_Listed': '2024-03-07',
  'Agent_ID': 'A0050',
  'Latitude': 39.5606135828,
  'Longitude': -115.1161514064},
 {'Listing_ID': 'L00017',
  'City': 'New York',
  'Property_Type': 'House',
  'Price': 1823443.991926888,
  'Sqft': 761.9910429221,
  'Date_Listed': '2024-02-17',
  'Agent_ID': 'A0021',
  'Latitude': 26.5653340022,
  'Longitude': -69.9599783535},
 {'Listing_ID': 'L00018',
  'City': 'Houston',
  'Property_Type': 'Condo',
  'Price': 238806.9991160855,
  'Sqft': 2228.0055864515,
  'Date_Listed': '2024-04-12',
  'Agent_ID': 'A0037',
  'Latitude': 48.1698905658,
  'Longitude': -78.1024236235},
 {'Listing_ID': 'L00019',
  'City': 'Chicago',
  'Property_Type': 'House',
  'Price': 1474553.9971662802,
  'Sqft': 4588.9969614987,
  'Date_Listed': '2023-07-22',
  'Agent_ID': 'A0042',
  'Latitude': 32.3174646036,
  'Longitude': -119.3352010399},
 {'Listing_ID': 'L00020',
  'City': 'Houston',
  'Property_Type': 'House',
  'Price': 655493.0037820246,
  'Sqft': 1642.993953628,
  'Date_Listed': '2023-05-07',
  'Agent_ID': 'A0048',
  'Latitude': 41.4292958213,
  'Longitude': -99.4574502664},
 {'Listing_ID': 'L00021',
  'City': 'Phoenix',
  'Property_Type': 'Condo',
  'Price': 1666600.9895170184,
  'Sqft': 4008.9978969856,
  'Date_Listed': '2024-04-04',
  'Agent_ID': 'A0038',
  'Latitude': 27.9290898341,
  'Longitude': -96.2830279906},
 {'Listing_ID': 'L00022',
  'City': 'Houston',
  'Property_Type': 'Condo',
  'Price': 559947.9922024726,
  'Sqft': 1632.9825852231,
  'Date_Listed': '2023-09-18',
  'Agent_ID': 'A0032',
  'Latitude': 25.8170831427,
  'Longitude': -72.269854559},
 {'Listing_ID': 'L00023',
  'City': 'New York',
  'Property_Type': 'Apartment',
  'Price': 1905862.998264031,
  'Sqft': 1398.000161607,
  'Date_Listed': '2023-03-20',
  'Agent_ID': 'A0041',
  'Latitude': 31.2208542412,
  'Longitude': -86.5858979497},
 {'Listing_ID': 'L00024',
  'City': 'Los Angeles',
  'Property_Type': 'Townhouse',
  'Price': 1350760.0032556157,
  'Sqft': 1019.9872054702,
  'Date_Listed': '2023-07-17',
  'Agent_ID': 'A0025',
  'Latitude': 32.4753814616,
  'Longitude': -94.8329238418},
 {'Listing_ID': 'L00025',
  'City': 'Phoenix',
  'Property_Type': 'Townhouse',
  'Price': 1209632.9979716954,
  'Sqft': 2558.9872529546,
  'Date_Listed': '2024-05-12',
  'Agent_ID': 'A0036',
  'Latitude': 38.119584411,
  'Longitude': -114.2548262935},
 {'Listing_ID': 'L00026',
  'City': 'New York',
  'Property_Type': 'Apartment',
  'Price': 1529650.007746305,
  'Sqft': 4897.9929195399,
  'Date_Listed': '2024-01-20',
  'Agent_ID': 'A0018',
  'Latitude': 48.2727660384,
  'Longitude': -80.0229214198},
 {'Listing_ID': 'L00027',
  'City': 'Chicago',
  'Property_Type': 'Apartment',
  'Price': 715514.0105212211,
  'Sqft': 4060.995356237,
  'Date_Listed': '2023-03-22',
  'Agent_ID': 'A0030',
  'Latitude': 47.5607962653,
  'Longitude': -73.0966404624},
 {'Listing_ID': 'L00028',
  'City': 'New York',
  'Property_Type': 'Condo',
  'Price': 1149805.022774446,
  'Sqft': 1963.0086161937,
  'Date_Listed': '2023-09-17',
  'Agent_ID': 'A0007',
  'Latitude': 39.3433736022,
  'Longitude': -71.5232101841},
 {'Listing_ID': 'L00029',
  'City': 'Chicago',
  'Property_Type': 'House',
  'Price': 420526.996362138,
  'Sqft': 3562.9998182924,
  'Date_Listed': '2024-01-26',
  'Agent_ID': 'A0011',
  'Latitude': 27.1258472438,
  'Longitude': -113.6176070274},
 {'Listing_ID': 'L00030',
  'City': 'Phoenix',
  'Property_Type': 'Apartment',
  'Price': 1356076.9997694592,
  'Sqft': 3155.0195611716,
  'Date_Listed': '2023-09-08',
  'Agent_ID': 'A0002',
  'Latitude': 26.0633829383,
  'Longitude': -106.1167797261},
 {'Listing_ID': 'L00031',
  'City': 'New York',
  'Property_Type': 'Condo',
  'Price': 1942813.0070935567,
  'Sqft': 3018.992756025,
  'Date_Listed': '2023-05-03',
  'Agent_ID': 'A0004',
  'Latitude': 34.3268415649,
  'Longitude': -109.2481520153},
 {'Listing_ID': 'L00032',
  'City': 'Los Angeles',
  'Property_Type': 'Apartment',
  'Price': 279627.9828940844,
  'Sqft': 4481.0033803764,
  'Date_Listed': '2024-02-22',
  'Agent_ID': 'A0005',
  'Latitude': 44.8886779321,
  'Longitude': -104.3088841328},
 {'Listing_ID': 'L00033',
  'City': 'Phoenix',
  'Property_Type': 'House',
  'Price': 369255.9867133461,
  'Sqft': 4392.9944753235,
  'Date_Listed': '2024-04-29',
  'Agent_ID': 'A0036',
  'Latitude': 31.7483050495,
  'Longitude': -93.5173568229},
 {'Listing_ID': 'L00034',
  'City': 'Los Angeles',
  'Property_Type': 'Condo',
  'Price': 1206612.0044058403,
  'Sqft': 3965.9999954926,
  'Date_Listed': '2024-05-08',
  'Agent_ID': 'A0014',
  'Latitude': 28.3954666469,
  'Longitude': -78.4792978709},
 {'Listing_ID': 'L00035',
  'City': 'Phoenix',
  'Property_Type': 'House',
  'Price': 1595162.0022436606,
  'Sqft': 3053.00445987,
  'Date_Listed': '2023-07-24',
  'Agent_ID': 'A0043',
  'Latitude': 26.7793816313,
  'Longitude': -67.7637654748},
 {'Listing_ID': 'L00036',
  'City': 'Chicago',
  'Property_Type': 'Townhouse',
  'Price': 1986626.9982937004,
  'Sqft': 4739.0106064016,
  'Date_Listed': '2023-08-20',
  'Agent_ID': 'A0008',
  'Latitude': 43.5497248799,
  'Longitude': -113.4803450916},
 {'Listing_ID': 'L00037',
  'City': 'Los Angeles',
  'Property_Type': 'House',
  'Price': 234271.9905708409,
  'Sqft': 3268.9973305329,
  'Date_Listed': '2023-01-11',
  'Agent_ID': 'A0038',
  'Latitude': 25.1271935888,
  'Longitude': -77.695743235},
 {'Listing_ID': 'L00038',
  'City': 'Phoenix',
  'Property_Type': 'House',
  'Price': 1334047.9847119623,
  'Sqft': 2303.9924302756,
  'Date_Listed': '2023-01-04',
  'Agent_ID': 'A0005',
  'Latitude': 41.9517778588,
  'Longitude': -82.7296416306},
 {'Listing_ID': 'L00039',
  'City': 'New York',
  'Property_Type': 'House',
  'Price': 241347.9937965968,
  'Sqft': 757.0172819014,
  'Date_Listed': '2024-03-16',
  'Agent_ID': 'A0022',
  'Latitude': 43.5149827054,
  'Longitude': -120.7095220006},
 {'Listing_ID': 'L00040',
  'City': 'New York',
  'Property_Type': 'House',
  'Price': 684009.001745823,
  'Sqft': 4475.9849570381,
  'Date_Listed': '2023-04-20',
  'Agent_ID': 'A0035',
  'Latitude': 33.6008881471,
  'Longitude': -118.2906497446},
 {'Listing_ID': 'L00041',
  'City': 'Los Angeles',
  'Property_Type': 'Townhouse',
  'Price': 609601.9933523665,
  'Sqft': 4373.9867944448,
  'Date_Listed': '2024-02-18',
  'Agent_ID': 'A0027',
  'Latitude': 45.7091560157,
  'Longitude': -88.8456795944},
 {'Listing_ID': 'L00042',
  'City': 'Los Angeles',
  'Property_Type': 'Apartment',
  'Price': 303278.0054376267,
  'Sqft': 4030.9858568846,
  'Date_Listed': '2023-07-01',
  'Agent_ID': 'A0028',
  'Latitude': 32.9466374501,
  'Longitude': -121.3245138112},
 {'Listing_ID': 'L00043',
  'City': 'Houston',
  'Property_Type': 'Townhouse',
  'Price': 1911596.0243525945,
  'Sqft': 943.006286233,
  'Date_Listed': '2023-12-11',
  'Agent_ID': 'A0042',
  'Latitude': 32.4683955586,
  'Longitude': -106.1345042263},
 {'Listing_ID': 'L00044',
  'City': 'New York',
  'Property_Type': 'Apartment',
  'Price': 944358.0060646946,
  'Sqft': 3278.9872164437,
  'Date_Listed': '2024-02-14',
  'Agent_ID': 'A0007',
  'Latitude': 42.5015929696,
  'Longitude': -88.0343341326},
 {'Listing_ID': 'L00045',
  'City': 'Los Angeles',
  'Property_Type': 'House',
  'Price': 498895.9931935394,
  'Sqft': 4892.9774985391,
  'Date_Listed': '2023-08-18',
  'Agent_ID': 'A0009',
  'Latitude': 46.2983679408,
  'Longitude': -97.6086290268},
 {'Listing_ID': 'L00046',
  'City': 'Houston',
  'Property_Type': 'House',
  'Price': 684150.9850024586,
  'Sqft': 4289.00371231,
  'Date_Listed': '2023-05-08',
  'Agent_ID': 'A0005',
  'Latitude': 27.8670510432,
  'Longitude': -83.628569518},
 {'Listing_ID': 'L00047',
  'City': 'Houston',
  'Property_Type': 'Apartment',
  'Price': 206090.992576832,
  'Sqft': 4928.0180862834,
  'Date_Listed': '2024-03-04',
  'Agent_ID': 'A0001',
  'Latitude': 43.2642502129,
  'Longitude': -92.4532509955},
 {'Listing_ID': 'L00048',
  'City': 'New York',
  'Property_Type': 'House',
  'Price': 448778.9907588365,
  'Sqft': 3829.0255823772,
  'Date_Listed': '2023-09-06',
  'Agent_ID': 'A0031',
  'Latitude': 43.4900156661,
  'Longitude': -96.3784651134},
 {'Listing_ID': 'L00049',
  'City': 'Los Angeles',
  'Property_Type': 'Townhouse',
  'Price': 1992558.993666205,
  'Sqft': 980.00891026,
  'Date_Listed': '2023-03-26',
  'Agent_ID': 'A0025',
  'Latitude': 37.5204776701,
  'Longitude': -100.2117923844},
 {'Listing_ID': 'L00050',
  'City': 'New York',
  'Property_Type': 'Townhouse',
  'Price': 656170.9985995548,
  'Sqft': 4226.9820195161,
  'Date_Listed': '2023-05-27',
  'Agent_ID': 'A0028',
  'Latitude': 25.6161133735,
  'Longitude': -118.7403679638},
 {'Listing_ID': 'L00051',
  'City': 'Phoenix',
  'Property_Type': 'Townhouse',
  'Price': 424631.9953986098,
  'Sqft': 2054.993811594,
  'Date_Listed': '2023-06-01',
  'Agent_ID': 'A0014',
  'Latitude': 25.761618658,
  'Longitude': -88.0936904528},
 {'Listing_ID': 'L00052',
  'City': 'New York',
  'Property_Type': 'Apartment',
  'Price': 1668617.9917311152,
  'Sqft': 3069.0072975525,
  'Date_Listed': '2023-01-30',
  'Agent_ID': 'A0004',
  'Latitude': 32.5388363135,
  'Longitude': -95.5066937821},
 {'Listing_ID': 'L00053',
  'City': 'Phoenix',
  'Property_Type': 'Townhouse',
  'Price': 1154553.014901774,
  'Sqft': 4850.0099341646,
  'Date_Listed': '2023-03-22',
  'Agent_ID': 'A0004',
  'Latitude': 46.7904185617,
  'Longitude': -110.5505869598},
 {'Listing_ID': 'L00054',
  'City': 'Phoenix',
  'Property_Type': 'Apartment',
  'Price': 1885394.0027651929,
  'Sqft': 2021.9877856247,
  'Date_Listed': '2023-02-05',
  'Agent_ID': 'A0039',
  'Latitude': 34.8462556861,
  'Longitude': -81.1700064354},
 {'Listing_ID': 'L00055',
  'City': 'New York',
  'Property_Type': 'House',
  'Price': 946777.9996189112,
  'Sqft': 1482.0179235242,
  'Date_Listed': '2024-04-27',
  'Agent_ID': 'A0037',
  'Latitude': 30.4651560146,
  'Longitude': -120.5369520762},
 {'Listing_ID': 'L00056',
  'City': 'Los Angeles',
  'Property_Type': 'Apartment',
  'Price': 1398936.992892045,
  'Sqft': 1170.9938551099,
  'Date_Listed': '2023-08-03',
  'Agent_ID': 'A0043',
  'Latitude': 31.9565278567,
  'Longitude': -115.6480486895},
 {'Listing_ID': 'L00057',
  'City': 'Phoenix',
  'Property_Type': 'Condo',
  'Price': 646864.9940109532,
  'Sqft': 2173.0043767088,
  'Date_Listed': '2023-12-09',
  'Agent_ID': 'A0046',
  'Latitude': 47.3112410926,
  'Longitude': -78.1135549335},
 {'Listing_ID': 'L00058',
  'City': 'Chicago',
  'Property_Type': 'House',
  'Price': 657034.0069895955,
  'Sqft': 3742.0086963294,
  'Date_Listed': '2023-03-09',
  'Agent_ID': 'A0043',
  'Latitude': 40.2086204548,
  'Longitude': -74.4404303747},
 {'Listing_ID': 'L00059',
  'City': 'Chicago',
  'Property_Type': 'Townhouse',
  'Price': 763071.0083974146,
  'Sqft': 1094.0041316585,
  'Date_Listed': '2023-01-05',
  'Agent_ID': 'A0030',
  'Latitude': 44.2827353761,
  'Longitude': -114.1803056648},
 {'Listing_ID': 'L00060',
  'City': 'Phoenix',
  'Property_Type': 'Apartment',
  'Price': 253638.0102558497,
  'Sqft': 4904.0151293379,
  'Date_Listed': '2023-04-20',
  'Agent_ID': 'A0033',
  'Latitude': 46.410717685,
  'Longitude': -93.7183101908},
 {'Listing_ID': 'L00061',
  'City': 'Chicago',
  'Property_Type': 'House',
  'Price': 831924.0092601049,
  'Sqft': 1063.0061280225,
  'Date_Listed': '2024-03-26',
  'Agent_ID': 'A0016',
  'Latitude': 44.3717180983,
  'Longitude': -73.0168938696},
 {'Listing_ID': 'L00062',
  'City': 'Chicago',
  'Property_Type': 'Condo',
  'Price': 430818.9959883752,
  'Sqft': 4089.0195665673,
  'Date_Listed': '2024-03-02',
  'Agent_ID': 'A0035',
  'Latitude': 32.6135712144,
  'Longitude': -118.6064141325},
 {'Listing_ID': 'L00063',
  'City': 'Chicago',
  'Property_Type': 'Apartment',
  'Price': 1500609.9979459555,
  'Sqft': 2952.009513741,
  'Date_Listed': '2024-04-22',
  'Agent_ID': 'A0043',
  'Latitude': 30.4851391176,
  'Longitude': -100.2187723825},
 {'Listing_ID': 'L00064',
  'City': 'New York',
  'Property_Type': 'House',
  'Price': 654625.0108844107,
  'Sqft': 1445.000395038,
  'Date_Listed': '2024-03-31',
  'Agent_ID': 'A0007',
  'Latitude': 44.6358264786,
  'Longitude': -75.0729908729},
 {'Listing_ID': 'L00065',
  'City': 'Phoenix',
  'Property_Type': 'House',
  'Price': 671155.0073553645,
  'Sqft': 2807.9897481108,
  'Date_Listed': '2023-11-06',
  'Agent_ID': 'A0014',
  'Latitude': 25.1796892095,
  'Longitude': -95.3779771634},
 {'Listing_ID': 'L00066',
  'City': 'Chicago',
  'Property_Type': 'House',
  'Price': 1541785.005881715,
  'Sqft': 2661.9948108116,
  'Date_Listed': '2023-09-16',
  'Agent_ID': 'A0032',
  'Latitude': 35.0154780669,
  'Longitude': -112.1028739339},
 {'Listing_ID': 'L00067',
  'City': 'Chicago',
  'Property_Type': 'Apartment',
  'Price': 293562.991705888,
  'Sqft': 3968.9890394132,
  'Date_Listed': '2024-02-29',
  'Agent_ID': 'A0018',
  'Latitude': 27.8864520562,
  'Longitude': -105.4113724066},
 {'Listing_ID': 'L00068',
  'City': 'New York',
  'Property_Type': 'Apartment',
  'Price': 799517.9931058761,
  'Sqft': 1571.0019832297,
  'Date_Listed': '2023-11-23',
  'Agent_ID': 'A0017',
  'Latitude': 47.6403206866,
  'Longitude': -106.2632255622},
 {'Listing_ID': 'L00069',
  'City': 'Los Angeles',
  'Property_Type': 'Townhouse',
  'Price': 1256957.0031506247,
  'Sqft': 4003.0114329256,
  'Date_Listed': '2023-10-15',
  'Agent_ID': 'A0001',
  'Latitude': 37.4431846551,
  'Longitude': -84.2371076936},
 {'Listing_ID': 'L00070',
  'City': 'New York',
  'Property_Type': 'Apartment',
  'Price': 1952008.0085800816,
  'Sqft': 1721.0087544017,
  'Date_Listed': '2023-10-07',
  'Agent_ID': 'A0003',
  'Latitude': 33.7097956441,
  'Longitude': -68.6340529765},
 {'Listing_ID': 'L00071',
  'City': 'Chicago',
  'Property_Type': 'House',
  'Price': 1001328.0130720296,
  'Sqft': 1544.016407825,
  'Date_Listed': '2023-01-22',
  'Agent_ID': 'A0020',
  'Latitude': 48.0783802554,
  'Longitude': -110.3936928378},
 {'Listing_ID': 'L00072',
  'City': 'Chicago',
  'Property_Type': 'Apartment',
  'Price': 1985180.9935530408,
  'Sqft': 3431.0139869652,
  'Date_Listed': '2023-04-18',
  'Agent_ID': 'A0044',
  'Latitude': 36.9180341978,
  'Longitude': -107.5494182588},
 {'Listing_ID': 'L00073',
  'City': 'Los Angeles',
  'Property_Type': 'Apartment',
  'Price': 841716.9942317429,
  'Sqft': 3829.0164019267,
  'Date_Listed': '2024-05-13',
  'Agent_ID': 'A0040',
  'Latitude': 31.8411503329,
  'Longitude': -122.8598128376},
 {'Listing_ID': 'L00074',
  'City': 'Los Angeles',
  'Property_Type': 'House',
  'Price': 1913209.0115324676,
  'Sqft': 1831.0142917551,
  'Date_Listed': '2024-05-14',
  'Agent_ID': 'A0012',
  'Latitude': 39.6170653256,
  'Longitude': -95.8650866912},
 {'Listing_ID': 'L00075',
  'City': 'Houston',
  'Property_Type': 'Apartment',
  'Price': 476145.995407261,
  'Sqft': 3220.989488528,
  'Date_Listed': '2024-02-05',
  'Agent_ID': 'A0027',
  'Latitude': 26.2321069187,
  'Longitude': -108.838532292},
 {'Listing_ID': 'L00076',
  'City': 'Los Angeles',
  'Property_Type': 'Condo',
  'Price': 433862.0290331536,
  'Sqft': 1384.9975128761,
  'Date_Listed': '2023-07-15',
  'Agent_ID': 'A0003',
  'Latitude': 46.7956695919,
  'Longitude': -111.0779120601},
 {'Listing_ID': 'L00077',
  'City': 'Houston',
  'Property_Type': 'House',
  'Price': 518534.0134712281,
  'Sqft': 4269.994796758,
  'Date_Listed': '2023-06-29',
  'Agent_ID': 'A0020',
  'Latitude': 28.4913285609,
  'Longitude': -96.6133456793},
 {'Listing_ID': 'L00078',
  'City': 'Los Angeles',
  'Property_Type': 'House',
  'Price': 149626.9962423429,
  'Sqft': 2082.0069999196,
  'Date_Listed': '2023-07-24',
  'Agent_ID': 'A0022',
  'Latitude': 48.6648289016,
  'Longitude': -110.9442572349},
 {'Listing_ID': 'L00079',
  'City': 'Chicago',
  'Property_Type': 'Apartment',
  'Price': 1721783.002609785,
  'Sqft': 2786.0017747648,
  'Date_Listed': '2023-06-29',
  'Agent_ID': 'A0042',
  'Latitude': 41.1255847944,
  'Longitude': -80.8146432293},
 {'Listing_ID': 'L00080',
  'City': 'Phoenix',
  'Property_Type': 'Townhouse',
  'Price': 1525051.9908902347,
  'Sqft': 4892.0016418842,
  'Date_Listed': '2023-06-19',
  'Agent_ID': 'A0002',

STEP 1: Read JSON Data (Python)

In [ ]:
import pandas as pd

# Read JSON files
listings_df = pd.read_json("listings_final_expanded.json")
property_df = pd.read_json("property_attributes_final_expanded.json")
agents_df = pd.read_json("agents_cleaned.json")
sales_df = pd.read_json("sales_cleaned.json")
buyers_df = pd.read_json("buyers_cleaned.json")

In [ ]:
listings_df.head()

In [ ]:
property_df.head(10)

In [2]:
import json
import pandas as pd

with open("listings_final_expanded.json", "r") as file:
    data = json.load(file)    #data is now a list of dictionaries

In [3]:
data

[{'Listing_ID': 'L00001',
  'City': 'New York',
  'Property_Type': 'Apartment',
  'Price': 1655144.006669635,
  'Sqft': 2753.009121237,
  'Date_Listed': '2023-05-06',
  'Agent_ID': 'A0015',
  'Latitude': 33.9652080059,
  'Longitude': -69.8615892795},
 {'Listing_ID': 'L00002',
  'City': 'Los Angeles',
  'Property_Type': 'Apartment',
  'Price': 1519141.0026169808,
  'Sqft': 4966.9881928135,
  'Date_Listed': '2023-02-14',
  'Agent_ID': 'A0038',
  'Latitude': 42.5478920594,
  'Longitude': -90.2778602519},
 {'Listing_ID': 'L00003',
  'City': 'Houston',
  'Property_Type': 'Apartment',
  'Price': 162488.9975420714,
  'Sqft': 1267.0039591344,
  'Date_Listed': '2023-04-22',
  'Agent_ID': 'A0015',
  'Latitude': 28.7323266553,
  'Longitude': -115.9529818783},
 {'Listing_ID': 'L00004',
  'City': 'Phoenix',
  'Property_Type': 'Apartment',
  'Price': 1277015.9840670894,
  'Sqft': 2128.0144287921,
  'Date_Listed': '2024-01-02',
  'Agent_ID': 'A0042',
  'Latitude': 26.4039382837,
  'Longitude': -74.7714904573},
 {'Listing_ID': 'L00005',
  'City': 'Phoenix',
  'Property_Type': 'Townhouse',
  'Price': 562297.0068077513,
  'Sqft': 4178.9974210875,
  'Date_Listed': '2023-10-29',
  'Agent_ID': 'A0018',
  'Latitude': 39.4252516293,
  'Longitude': -83.9178782667},
 {'Listing_ID': 'L00006',
  'City': 'New York',
  'Property_Type': 'House',
  'Price': 1564104.0078713011,
  'Sqft': 3961.992615551,
  'Date_Listed': '2023-06-24',
  'Agent_ID': 'A0018',
  'Latitude': 25.4877926032,
  'Longitude': -68.7571139192},
 {'Listing_ID': 'L00007',
  'City': 'Los Angeles',
  'Property_Type': 'House',
  'Price': 1701163.003815294,
  'Sqft': 3257.0150616858,
  'Date_Listed': '2023-02-22',
  'Agent_ID': 'A0006',
  'Latitude': 44.9691124588,
  'Longitude': -112.6784942679},
 {'Listing_ID': 'L00008',
  'City': 'Houston',
  'Property_Type': 'Apartment',
  'Price': 852834.0147462517,
  'Sqft': 3316.9937214813,
  'Date_Listed': '2023-11-06',
  'Agent_ID': 'A0017',
  'Latitude': 29.3549128014,
  'Longitude': -114.3646813823},
 {'Listing_ID': 'L00009',
  'City': 'New York',
  'Property_Type': 'Townhouse',
  'Price': 1224550.9990439962,
  'Sqft': 1522.0077799342,
  'Date_Listed': '2024-05-13',
  'Agent_ID': 'A0025',
  'Latitude': 32.3025694404,
  'Longitude': -94.5569819185},
 {'Listing_ID': 'L00010',
  'City': 'New York',
  'Property_Type': 'Condo',
  'Price': 1839386.9924549507,
  'Sqft': 3462.0226393851,
  'Date_Listed': '2023-10-23',
  'Agent_ID': 'A0013',
  'Latitude': 35.3703968658,
  'Longitude': -108.1193181126},
 {'Listing_ID': 'L00011',
  'City': 'New York',
  'Property_Type': 'Apartment',
  'Price': 1486768.99430001,
  'Sqft': 2366.0004685872,
  'Date_Listed': '2024-01-31',
  'Agent_ID': 'A0019',
  'Latitude': 39.6667837428,
  'Longitude': -116.9028968424},
 {'Listing_ID': 'L00012',
  'City': 'New York',
  'Property_Type': 'House',
  'Price': 1917147.0045034816,
  'Sqft': 1326.9966016133,
  'Date_Listed': '2023-07-14',
  'Agent_ID': 'A0018',
  'Latitude': 32.0067048962,
  'Longitude': -103.728939014},
 {'Listing_ID': 'L00013',
  'City': 'Houston',
  'Property_Type': 'Condo',
  'Price': 441109.9971346703,
  'Sqft': 3532.0009552261,
  'Date_Listed': '2023-07-01',
  'Agent_ID': 'A0014',
  'Latitude': 35.9403141234,
  'Longitude': -79.4629622952},
 {'Listing_ID': 'L00014',
  'City': 'Chicago',
  'Property_Type': 'Apartment',
  'Price': 1377440.009039592,
  'Sqft': 1900.9981292033,
  'Date_Listed': '2023-10-01',
  'Agent_ID': 'A0047',
  'Latitude': 29.7726767961,
  'Longitude': -95.1627789955},
 {'Listing_ID': 'L00015',
  'City': 'Los Angeles',
  'Property_Type': 'House',
  'Price': 1069428.9949294312,
  'Sqft': 3607.9958386703,
  'Date_Listed': '2023-05-19',
  'Agent_ID': 'A0041',
  'Latitude': 39.2149977097,
  'Longitude': -122.2951451057},
 {'Listing_ID': 'L00016',
  'City': 'Phoenix',
  'Property_Type': 'House',
  'Price': 1535739.9878467089,
  'Sqft': 3155.9855295615,
  'Date_Listed': '2024-03-07',
  'Agent_ID': 'A0050',
  'Latitude': 39.5606135828,
  'Longitude': -115.1161514064},
 {'Listing_ID': 'L00017',
  'City': 'New York',
  'Property_Type': 'House',
  'Price': 1823443.991926888,
  'Sqft': 761.9910429221,
  'Date_Listed': '2024-02-17',
  'Agent_ID': 'A0021',
  'Latitude': 26.5653340022,
  'Longitude': -69.9599783535},
 {'Listing_ID': 'L00018',
  'City': 'Houston',
  'Property_Type': 'Condo',
  'Price': 238806.9991160855,
  'Sqft': 2228.0055864515,
  'Date_Listed': '2024-04-12',
  'Agent_ID': 'A0037',
  'Latitude': 48.1698905658,
  'Longitude': -78.1024236235},
 {'Listing_ID': 'L00019',
  'City': 'Chicago',
  'Property_Type': 'House',
  'Price': 1474553.9971662802,
  'Sqft': 4588.9969614987,
  'Date_Listed': '2023-07-22',
  'Agent_ID': 'A0042',
  'Latitude': 32.3174646036,
  'Longitude': -119.3352010399},
 {'Listing_ID': 'L00020',
  'City': 'Houston',
  'Property_Type': 'House',
  'Price': 655493.0037820246,
  'Sqft': 1642.993953628,
  'Date_Listed': '2023-05-07',
  'Agent_ID': 'A0048',
  'Latitude': 41.4292958213,
  'Longitude': -99.4574502664},
 {'Listing_ID': 'L00021',
  'City': 'Phoenix',
  'Property_Type': 'Condo',
  'Price': 1666600.9895170184,
  'Sqft': 4008.9978969856,
  'Date_Listed': '2024-04-04',
  'Agent_ID': 'A0038',
  'Latitude': 27.9290898341,
  'Longitude': -96.2830279906},
 {'Listing_ID': 'L00022',
  'City': 'Houston',
  'Property_Type': 'Condo',
  'Price': 559947.9922024726,
  'Sqft': 1632.9825852231,
  'Date_Listed': '2023-09-18',
  'Agent_ID': 'A0032',
  'Latitude': 25.8170831427,
  'Longitude': -72.269854559},
 {'Listing_ID': 'L00023',
  'City': 'New York',
  'Property_Type': 'Apartment',
  'Price': 1905862.998264031,
  'Sqft': 1398.000161607,
  'Date_Listed': '2023-03-20',
  'Agent_ID': 'A0041',
  'Latitude': 31.2208542412,
  'Longitude': -86.5858979497},
 {'Listing_ID': 'L00024',
  'City': 'Los Angeles',
  'Property_Type': 'Townhouse',
  'Price': 1350760.0032556157,
  'Sqft': 1019.9872054702,
  'Date_Listed': '2023-07-17',
  'Agent_ID': 'A0025',
  'Latitude': 32.4753814616,
  'Longitude': -94.8329238418},
 {'Listing_ID': 'L00025',
  'City': 'Phoenix',
  'Property_Type': 'Townhouse',
  'Price': 1209632.9979716954,
  'Sqft': 2558.9872529546,
  'Date_Listed': '2024-05-12',
  'Agent_ID': 'A0036',
  'Latitude': 38.119584411,
  'Longitude': -114.2548262935},
 {'Listing_ID': 'L00026',
  'City': 'New York',
  'Property_Type': 'Apartment',
  'Price': 1529650.007746305,
  'Sqft': 4897.9929195399,
  'Date_Listed': '2024-01-20',
  'Agent_ID': 'A0018',
  'Latitude': 48.2727660384,
  'Longitude': -80.0229214198},
 {'Listing_ID': 'L00027',
  'City': 'Chicago',
  'Property_Type': 'Apartment',
  'Price': 715514.0105212211,
  'Sqft': 4060.995356237,
  'Date_Listed': '2023-03-22',
  'Agent_ID': 'A0030',
  'Latitude': 47.5607962653,
  'Longitude': -73.0966404624},
 {'Listing_ID': 'L00028',
  'City': 'New York',
  'Property_Type': 'Condo',
  'Price': 1149805.022774446,
  'Sqft': 1963.0086161937,
  'Date_Listed': '2023-09-17',
  'Agent_ID': 'A0007',
  'Latitude': 39.3433736022,
  'Longitude': -71.5232101841},
 {'Listing_ID': 'L00029',
  'City': 'Chicago',
  'Property_Type': 'House',
  'Price': 420526.996362138,
  'Sqft': 3562.9998182924,
  'Date_Listed': '2024-01-26',
  'Agent_ID': 'A0011',
  'Latitude': 27.1258472438,
  'Longitude': -113.6176070274},
 {'Listing_ID': 'L00030',
  'City': 'Phoenix',
  'Property_Type': 'Apartment',
  'Price': 1356076.9997694592,
  'Sqft': 3155.0195611716,
  'Date_Listed': '2023-09-08',
  'Agent_ID': 'A0002',
  'Latitude': 26.0633829383,
  'Longitude': -106.1167797261},
 {'Listing_ID': 'L00031',
  'City': 'New York',
  'Property_Type': 'Condo',
  'Price': 1942813.0070935567,
  'Sqft': 3018.992756025,
  'Date_Listed': '2023-05-03',
  'Agent_ID': 'A0004',
  'Latitude': 34.3268415649,
  'Longitude': -109.2481520153},
 {'Listing_ID': 'L00032',
  'City': 'Los Angeles',
  'Property_Type': 'Apartment',
  'Price': 279627.9828940844,
  'Sqft': 4481.0033803764,
  'Date_Listed': '2024-02-22',
  'Agent_ID': 'A0005',
  'Latitude': 44.8886779321,
  'Longitude': -104.3088841328},
 {'Listing_ID': 'L00033',
  'City': 'Phoenix',
  'Property_Type': 'House',
  'Price': 369255.9867133461,
  'Sqft': 4392.9944753235,
  'Date_Listed': '2024-04-29',
  'Agent_ID': 'A0036',
  'Latitude': 31.7483050495,
  'Longitude': -93.5173568229},
 {'Listing_ID': 'L00034',
  'City': 'Los Angeles',
  'Property_Type': 'Condo',
  'Price': 1206612.0044058403,
  'Sqft': 3965.9999954926,
  'Date_Listed': '2024-05-08',
  'Agent_ID': 'A0014',
  'Latitude': 28.3954666469,
  'Longitude': -78.4792978709},
 {'Listing_ID': 'L00035',
  'City': 'Phoenix',
  'Property_Type': 'House',
  'Price': 1595162.0022436606,
  'Sqft': 3053.00445987,
  'Date_Listed': '2023-07-24',
  'Agent_ID': 'A0043',
  'Latitude': 26.7793816313,
  'Longitude': -67.7637654748},
 {'Listing_ID': 'L00036',
  'City': 'Chicago',
  'Property_Type': 'Townhouse',
  'Price': 1986626.9982937004,
  'Sqft': 4739.0106064016,
  'Date_Listed': '2023-08-20',
  'Agent_ID': 'A0008',
  'Latitude': 43.5497248799,
  'Longitude': -113.4803450916},
 {'Listing_ID': 'L00037',
  'City': 'Los Angeles',
  'Property_Type': 'House',
  'Price': 234271.9905708409,
  'Sqft': 3268.9973305329,
  'Date_Listed': '2023-01-11',
  'Agent_ID': 'A0038',
  'Latitude': 25.1271935888,
  'Longitude': -77.695743235},
 {'Listing_ID': 'L00038',
  'City': 'Phoenix',
  'Property_Type': 'House',
  'Price': 1334047.9847119623,
  'Sqft': 2303.9924302756,
  'Date_Listed': '2023-01-04',
  'Agent_ID': 'A0005',
  'Latitude': 41.9517778588,
  'Longitude': -82.7296416306},
 {'Listing_ID': 'L00039',
  'City': 'New York',
  'Property_Type': 'House',
  'Price': 241347.9937965968,
  'Sqft': 757.0172819014,
  'Date_Listed': '2024-03-16',
  'Agent_ID': 'A0022',
  'Latitude': 43.5149827054,
  'Longitude': -120.7095220006},
 {'Listing_ID': 'L00040',
  'City': 'New York',
  'Property_Type': 'House',
  'Price': 684009.001745823,
  'Sqft': 4475.9849570381,
  'Date_Listed': '2023-04-20',
  'Agent_ID': 'A0035',
  'Latitude': 33.6008881471,
  'Longitude': -118.2906497446},
 {'Listing_ID': 'L00041',
  'City': 'Los Angeles',
  'Property_Type': 'Townhouse',
  'Price': 609601.9933523665,
  'Sqft': 4373.9867944448,
  'Date_Listed': '2024-02-18',
  'Agent_ID': 'A0027',
  'Latitude': 45.7091560157,
  'Longitude': -88.8456795944},
 {'Listing_ID': 'L00042',
  'City': 'Los Angeles',
  'Property_Type': 'Apartment',
  'Price': 303278.0054376267,
  'Sqft': 4030.9858568846,
  'Date_Listed': '2023-07-01',
  'Agent_ID': 'A0028',
  'Latitude': 32.9466374501,
  'Longitude': -121.3245138112},
 {'Listing_ID': 'L00043',
  'City': 'Houston',
  'Property_Type': 'Townhouse',
  'Price': 1911596.0243525945,
  'Sqft': 943.006286233,
  'Date_Listed': '2023-12-11',
  'Agent_ID': 'A0042',
  'Latitude': 32.4683955586,
  'Longitude': -106.1345042263},
 {'Listing_ID': 'L00044',
  'City': 'New York',
  'Property_Type': 'Apartment',
  'Price': 944358.0060646946,
  'Sqft': 3278.9872164437,
  'Date_Listed': '2024-02-14',
  'Agent_ID': 'A0007',
  'Latitude': 42.5015929696,
  'Longitude': -88.0343341326},
 {'Listing_ID': 'L00045',
  'City': 'Los Angeles',
  'Property_Type': 'House',
  'Price': 498895.9931935394,
  'Sqft': 4892.9774985391,
  'Date_Listed': '2023-08-18',
  'Agent_ID': 'A0009',
  'Latitude': 46.2983679408,
  'Longitude': -97.6086290268},
 {'Listing_ID': 'L00046',
  'City': 'Houston',
  'Property_Type': 'House',
  'Price': 684150.9850024586,
  'Sqft': 4289.00371231,
  'Date_Listed': '2023-05-08',
  'Agent_ID': 'A0005',
  'Latitude': 27.8670510432,
  'Longitude': -83.628569518},
 {'Listing_ID': 'L00047',
  'City': 'Houston',
  'Property_Type': 'Apartment',
  'Price': 206090.992576832,
  'Sqft': 4928.0180862834,
  'Date_Listed': '2024-03-04',
  'Agent_ID': 'A0001',
  'Latitude': 43.2642502129,
  'Longitude': -92.4532509955},
 {'Listing_ID': 'L00048',
  'City': 'New York',
  'Property_Type': 'House',
  'Price': 448778.9907588365,
  'Sqft': 3829.0255823772,
  'Date_Listed': '2023-09-06',
  'Agent_ID': 'A0031',
  'Latitude': 43.4900156661,
  'Longitude': -96.3784651134},
 {'Listing_ID': 'L00049',
  'City': 'Los Angeles',
  'Property_Type': 'Townhouse',
  'Price': 1992558.993666205,
  'Sqft': 980.00891026,
  'Date_Listed': '2023-03-26',
  'Agent_ID': 'A0025',
  'Latitude': 37.5204776701,
  'Longitude': -100.2117923844},
 {'Listing_ID': 'L00050',
  'City': 'New York',
  'Property_Type': 'Townhouse',
  'Price': 656170.9985995548,
  'Sqft': 4226.9820195161,
  'Date_Listed': '2023-05-27',
  'Agent_ID': 'A0028',
  'Latitude': 25.6161133735,
  'Longitude': -118.7403679638},
 {'Listing_ID': 'L00051',
  'City': 'Phoenix',
  'Property_Type': 'Townhouse',
  'Price': 424631.9953986098,
  'Sqft': 2054.993811594,
  'Date_Listed': '2023-06-01',
  'Agent_ID': 'A0014',
  'Latitude': 25.761618658,
  'Longitude': -88.0936904528},
 {'Listing_ID': 'L00052',
  'City': 'New York',
  'Property_Type': 'Apartment',
  'Price': 1668617.9917311152,
  'Sqft': 3069.0072975525,
  'Date_Listed': '2023-01-30',
  'Agent_ID': 'A0004',
  'Latitude': 32.5388363135,
  'Longitude': -95.5066937821},
 {'Listing_ID': 'L00053',
  'City': 'Phoenix',
  'Property_Type': 'Townhouse',
  'Price': 1154553.014901774,
  'Sqft': 4850.0099341646,
  'Date_Listed': '2023-03-22',
  'Agent_ID': 'A0004',
  'Latitude': 46.7904185617,
  'Longitude': -110.5505869598},
 {'Listing_ID': 'L00054',
  'City': 'Phoenix',
  'Property_Type': 'Apartment',
  'Price': 1885394.0027651929,
  'Sqft': 2021.9877856247,
  'Date_Listed': '2023-02-05',
  'Agent_ID': 'A0039',
  'Latitude': 34.8462556861,
  'Longitude': -81.1700064354},
 {'Listing_ID': 'L00055',
  'City': 'New York',
  'Property_Type': 'House',
  'Price': 946777.9996189112,
  'Sqft': 1482.0179235242,
  'Date_Listed': '2024-04-27',
  'Agent_ID': 'A0037',
  'Latitude': 30.4651560146,
  'Longitude': -120.5369520762},
 {'Listing_ID': 'L00056',
  'City': 'Los Angeles',
  'Property_Type': 'Apartment',
  'Price': 1398936.992892045,
  'Sqft': 1170.9938551099,
  'Date_Listed': '2023-08-03',
  'Agent_ID': 'A0043',
  'Latitude': 31.9565278567,
  'Longitude': -115.6480486895},
 {'Listing_ID': 'L00057',
  'City': 'Phoenix',
  'Property_Type': 'Condo',
  'Price': 646864.9940109532,
  'Sqft': 2173.0043767088,
  'Date_Listed': '2023-12-09',
  'Agent_ID': 'A0046',
  'Latitude': 47.3112410926,
  'Longitude': -78.1135549335},
 {'Listing_ID': 'L00058',
  'City': 'Chicago',
  'Property_Type': 'House',
  'Price': 657034.0069895955,
  'Sqft': 3742.0086963294,
  'Date_Listed': '2023-03-09',
  'Agent_ID': 'A0043',
  'Latitude': 40.2086204548,
  'Longitude': -74.4404303747},
 {'Listing_ID': 'L00059',
  'City': 'Chicago',
  'Property_Type': 'Townhouse',
  'Price': 763071.0083974146,
  'Sqft': 1094.0041316585,
  'Date_Listed': '2023-01-05',
  'Agent_ID': 'A0030',
  'Latitude': 44.2827353761,
  'Longitude': -114.1803056648},
 {'Listing_ID': 'L00060',
  'City': 'Phoenix',
  'Property_Type': 'Apartment',
  'Price': 253638.0102558497,
  'Sqft': 4904.0151293379,
  'Date_Listed': '2023-04-20',
  'Agent_ID': 'A0033',
  'Latitude': 46.410717685,
  'Longitude': -93.7183101908},
 {'Listing_ID': 'L00061',
  'City': 'Chicago',
  'Property_Type': 'House',
  'Price': 831924.0092601049,
  'Sqft': 1063.0061280225,
  'Date_Listed': '2024-03-26',
  'Agent_ID': 'A0016',
  'Latitude': 44.3717180983,
  'Longitude': -73.0168938696},
 {'Listing_ID': 'L00062',
  'City': 'Chicago',
  'Property_Type': 'Condo',
  'Price': 430818.9959883752,
  'Sqft': 4089.0195665673,
  'Date_Listed': '2024-03-02',
  'Agent_ID': 'A0035',
  'Latitude': 32.6135712144,
  'Longitude': -118.6064141325},
 {'Listing_ID': 'L00063',
  'City': 'Chicago',
  'Property_Type': 'Apartment',
  'Price': 1500609.9979459555,
  'Sqft': 2952.009513741,
  'Date_Listed': '2024-04-22',
  'Agent_ID': 'A0043',
  'Latitude': 30.4851391176,
  'Longitude': -100.2187723825},
 {'Listing_ID': 'L00064',
  'City': 'New York',
  'Property_Type': 'House',
  'Price': 654625.0108844107,
  'Sqft': 1445.000395038,
  'Date_Listed': '2024-03-31',
  'Agent_ID': 'A0007',
  'Latitude': 44.6358264786,
  'Longitude': -75.0729908729},
 {'Listing_ID': 'L00065',
  'City': 'Phoenix',
  'Property_Type': 'House',
  'Price': 671155.0073553645,
  'Sqft': 2807.9897481108,
  'Date_Listed': '2023-11-06',
  'Agent_ID': 'A0014',
  'Latitude': 25.1796892095,
  'Longitude': -95.3779771634},
 {'Listing_ID': 'L00066',
  'City': 'Chicago',
  'Property_Type': 'House',
  'Price': 1541785.005881715,
  'Sqft': 2661.9948108116,
  'Date_Listed': '2023-09-16',
  'Agent_ID': 'A0032',
  'Latitude': 35.0154780669,
  'Longitude': -112.1028739339},
 {'Listing_ID': 'L00067',
  'City': 'Chicago',
  'Property_Type': 'Apartment',
  'Price': 293562.991705888,
  'Sqft': 3968.9890394132,
  'Date_Listed': '2024-02-29',
  'Agent_ID': 'A0018',
  'Latitude': 27.8864520562,
  'Longitude': -105.4113724066},
 {'Listing_ID': 'L00068',
  'City': 'New York',
  'Property_Type': 'Apartment',
  'Price': 799517.9931058761,
  'Sqft': 1571.0019832297,
  'Date_Listed': '2023-11-23',
  'Agent_ID': 'A0017',
  'Latitude': 47.6403206866,
  'Longitude': -106.2632255622},
 {'Listing_ID': 'L00069',
  'City': 'Los Angeles',
  'Property_Type': 'Townhouse',
  'Price': 1256957.0031506247,
  'Sqft': 4003.0114329256,
  'Date_Listed': '2023-10-15',
  'Agent_ID': 'A0001',
  'Latitude': 37.4431846551,
  'Longitude': -84.2371076936},
 {'Listing_ID': 'L00070',
  'City': 'New York',
  'Property_Type': 'Apartment',
  'Price': 1952008.0085800816,
  'Sqft': 1721.0087544017,
  'Date_Listed': '2023-10-07',
  'Agent_ID': 'A0003',
  'Latitude': 33.7097956441,
  'Longitude': -68.6340529765},
 {'Listing_ID': 'L00071',
  'City': 'Chicago',
  'Property_Type': 'House',
  'Price': 1001328.0130720296,
  'Sqft': 1544.016407825,
  'Date_Listed': '2023-01-22',
  'Agent_ID': 'A0020',
  'Latitude': 48.0783802554,
  'Longitude': -110.3936928378},
 {'Listing_ID': 'L00072',
  'City': 'Chicago',
  'Property_Type': 'Apartment',
  'Price': 1985180.9935530408,
  'Sqft': 3431.0139869652,
  'Date_Listed': '2023-04-18',
  'Agent_ID': 'A0044',
  'Latitude': 36.9180341978,
  'Longitude': -107.5494182588},
 {'Listing_ID': 'L00073',
  'City': 'Los Angeles',
  'Property_Type': 'Apartment',
  'Price': 841716.9942317429,
  'Sqft': 3829.0164019267,
  'Date_Listed': '2024-05-13',
  'Agent_ID': 'A0040',
  'Latitude': 31.8411503329,
  'Longitude': -122.8598128376},
 {'Listing_ID': 'L00074',
  'City': 'Los Angeles',
  'Property_Type': 'House',
  'Price': 1913209.0115324676,
  'Sqft': 1831.0142917551,
  'Date_Listed': '2024-05-14',
  'Agent_ID': 'A0012',
  'Latitude': 39.6170653256,
  'Longitude': -95.8650866912},
 {'Listing_ID': 'L00075',
  'City': 'Houston',
  'Property_Type': 'Apartment',
  'Price': 476145.995407261,
  'Sqft': 3220.989488528,
  'Date_Listed': '2024-02-05',
  'Agent_ID': 'A0027',
  'Latitude': 26.2321069187,
  'Longitude': -108.838532292},
 {'Listing_ID': 'L00076',
  'City': 'Los Angeles',
  'Property_Type': 'Condo',
  'Price': 433862.0290331536,
  'Sqft': 1384.9975128761,
  'Date_Listed': '2023-07-15',
  'Agent_ID': 'A0003',
  'Latitude': 46.7956695919,
  'Longitude': -111.0779120601},
 {'Listing_ID': 'L00077',
  'City': 'Houston',
  'Property_Type': 'House',
  'Price': 518534.0134712281,
  'Sqft': 4269.994796758,
  'Date_Listed': '2023-06-29',
  'Agent_ID': 'A0020',
  'Latitude': 28.4913285609,
  'Longitude': -96.6133456793},
 {'Listing_ID': 'L00078',
  'City': 'Los Angeles',
  'Property_Type': 'House',
  'Price': 149626.9962423429,
  'Sqft': 2082.0069999196,
  'Date_Listed': '2023-07-24',
  'Agent_ID': 'A0022',
  'Latitude': 48.6648289016,
  'Longitude': -110.9442572349},
 {'Listing_ID': 'L00079',
  'City': 'Chicago',
  'Property_Type': 'Apartment',
  'Price': 1721783.002609785,
  'Sqft': 2786.0017747648,
  'Date_Listed': '2023-06-29',
  'Agent_ID': 'A0042',
  'Latitude': 41.1255847944,
  'Longitude': -80.8146432293},
 {'Listing_ID': 'L00080',
  'City': 'Phoenix',
  'Property_Type': 'Townhouse',
  'Price': 1525051.9908902347,
  'Sqft': 4892.0016418842,
  'Date_Listed': '2023-06-19',
  'Agent_ID': 'A0002',

In [8]:
import pandas as pd
df = pd.read_csv("sales_cleaned.csv")
df.to_json("sales_cleaned.json", index=False)
print("json file created successfully.")

json file created successfully.

In [9]:
import pandas as pd

# Read JSON files
listings_df = pd.read_json("listings_final_expanded.json")
property_df = pd.read_json("property_attributes_final_expanded.json")
agents_df = pd.read_json("agents_cleaned.json")
sales_df = pd.read_json("sales_cleaned.json")
buyers_df = pd.read_json("buyers_cleaned.json")

In [10]:
listings_df.head()

,Listing_ID,City,Property_Type,Price,Sqft,Date_Listed,Agent_ID,Latitude,Longitude
0,L00001,New York,Apartment,1.655144e+06,2753.009121,2023-05-06,A0015,33.965208,-69.861589
1,L00002,Los Angeles,Apartment,1.519141e+06,4966.988193,2023-02-14,A0038,42.547892,-90.277860
2,L00003,Houston,Apartment,1.624890e+05,1267.003959,2023-04-22,A0015,28.732327,-115.952982
3,L00004,Phoenix,Apartment,1.277016e+06,2128.014429,2024-01-02,A0042,26.403938,-74.771490
4,L00005,Phoenix,Townhouse,5.622970e+05,4178.997421,2023-10-29,A0018,39.425252,-83.917878

In [11]:
property_df.head()

,attribute_id,listing_id,bedrooms,bathrooms,floor_number,total_floors,year_built,is_rented,tenant_count,furnishing_status,metro_distance_km,parking_available,power_backup
0,1,L00001,5,3,9,9,2001,True,4,Furnished,7.26,False,True
1,2,L00002,2,2,19,29,2020,False,0,Unfurnished,4.84,True,False
2,3,L00003,2,3,8,26,2007,True,4,Semi-Furnished,4.92,False,False
3,4,L00004,3,3,25,10,2003,False,3,Furnished,1.20,False,True
4,5,L00005,2,2,15,16,2008,True,1,Semi-Furnished,7.90,False,False

In [12]:
agents_df.head()

  Listing_ID    Sale_Price   Date_Sold  Days_on_Market
0     L01179  9.255800e+05  2023-07-07       65.005560
1     L00866  1.054160e+05  2023-06-14       38.004620
2     L00102  1.825184e+06  2023-09-09       22.992622
3     L00440  1.932085e+06  2023-10-29       72.012274
4     L00059  7.765860e+05  2023-05-01      116.000152

In [13]:
sales_df.head()

  Listing_ID    Sale_Price   Date_Sold  Days_on_Market
0     L01179  9.255800e+05  2023-07-07       65.005560
1     L00866  1.054160e+05  2023-06-14       38.004620
2     L00102  1.825184e+06  2023-09-09       22.992622
3     L00440  1.932085e+06  2023-10-29       72.012274
4     L00059  7.765860e+05  2023-05-01      116.000152

In [14]:
buyers_df.head()

,buyer_id,sale_id,buyer_type,payment_mode,loan_taken,loan_provider,loan_amount
0,1,L01179,End User,Cash,False,None,0
1,2,L00866,Investor,Cheque,False,None,0
2,3,L00102,Investor,Cheque,True,Axis,2317757
3,4,L00440,Investor,Bank Transfer,False,None,0
4,5,L00059,Investor,UPI,True,HDFC,4191221

STEP 2: Connect to SQLite3

In [15]:
import sqlite3

In [6]:
# Create / connect database
conn = sqlite3.connect("brickview_realstate.db")
cursor = conn.cursor()

In [19]:
create_listings_table = """
CREATE TABLE IF NOT EXISTS listings(
    listings_id INTEGER PRIMARY KEY,
    address TEXT,
    city TEXT,
    state TEXT,
    zip TEXT,
    property_type TEXT,
    price REAL,
    area_sqft REAL,
    agent_id INTEGER,
    listed_date DATE
);
"""
cursor.execute(create_listings_table)
conn.commit()

In [20]:
cursor.execute("PRAGMA table_info(listings);")
columns = cursor.fetchall()

for col in columns:
    print(col)

(0, 'listings_id', 'INTEGER', 0, None, 1)
(1, 'address', 'TEXT', 0, None, 0)
(2, 'city', 'TEXT', 0, None, 0)
(3, 'state', 'TEXT', 0, None, 0)
(4, 'zip', 'TEXT', 0, None, 0)
(5, 'property_type', 'TEXT', 0, None, 0)
(6, 'price', 'REAL', 0, None, 0)
(7, 'area_sqft', 'REAL', 0, None, 0)
(8, 'agent_id', 'INTEGER', 0, None, 0)
(9, 'listed_date', 'DATE', 0, None, 0)

In [22]:
create_property_attributes_table = """
CREATE TABLE IF NOT EXISTS property_attributes(
    attribute_id INTEGER PRIMARY KEY,
    listing_id INTEGER,
    bedrooms INTEGER,
    bathrooms INTEGER,
    floor_number INTEGER,
    total_floors INTEGER,
    year_built INTEGER,
    is_rented BOOLEAN,
    tenant_count INTEGER,
    furnishing_status TEXT,
    metro_distance_km REAL,
    parking_available BOOLEAN,
    power_backup BOOLEAN,
    FOREIGN KEY (listing_id) REFERENCES listings(listing_id)
);
"""

cursor.execute(create_property_attributes_table)
conn.commit()

In [3]:
import sqlite3

In [4]:
conn = sqlite3.connect("brickview_realstate.db")
cursor = conn.cursor()

In [5]:
create_agents_cleaned_table = """
CREATE TABLE IF NOT EXISTS agents(
    agents_id INTEGER PRIMARY KEY,
    name TEXT,
    city TEXT,
    contact TEXT
);
"""
cursor.execute(create_agents_cleaned_table)
conn.commit()

In [7]:
create_sales_cleaned_table = """
CREATE TABLE IF NOT EXISTS sales(
    sales_id INTEGER PRIMARY KEY,
    listing_id INTEGER,
    sale_date DATE,
    sale_price REAL,
    days_on_market INTEGER,
    FOREIGN KEY (listing_id) REFERENCES listings(listing_id)
);
"""
cursor.execute(create_sales_cleaned_table)
conn.commit()

In [8]:
create_buyers_cleaned_table = """
CREATE TABLE IF NOT EXISTS buyers(
    buyers_id INTEGER PRIMARY KEY,
    sale_id INTEGER,
    buyer_type TEXT,
    payment_mode TEXT,
    loan_taken BOOLEAN,
    loan_provider TEXT,
    loan_amount REAL,
    FOREIGN KEY (sale_id) REFERENCES sales(sale_id)
);
"""
cursor.execute(create_buyers_cleaned_table)
conn.commit()

In [14]:
%who

conn	 create_agents_cleaned_table	 create_buyers_cleaned_table	 create_sales_cleaned_table	 cursor	 sqlite3

In [15]:
import sqlite3
conn = sqlite3.connect("brickview_realstate.db")
cursor = conn.cursor()

In [17]:
import pandas as pd

listings_df = pd.read_csv("listings_final_expanded.csv")
property_df = pd.read_csv("property_attributes_final_expanded.csv")
agents_df = pd.read_csv("agents_cleaned.csv")
sales_df = pd.read_csv("sales_cleaned.csv")
buyers_df = pd.read_csv("buyers_cleaned.csv")

listings_df.to_sql("listings", conn, if_exists="replace", index=False)
property_df.to_sql("property_attributes", conn, if_exists="replace", index=False)
agents_df.to_sql("agents", conn, if_exists="replace", index=False)
sales_df.to_sql("sales", conn, if_exists="replace", index=False)
buyers_df.to_sql("buyers", conn, if_exists="replace", index=False)

20000

In [18]:
listings_df.to_sql("listings", conn, if_exists="replace", index=False)

21200

In [19]:
property_df.to_sql("property_attributes", conn, if_exists="replace", index=False)

21200

In [20]:
agents_df.to_sql("agents", conn, if_exists="replace", index=False)

50

In [21]:
sales_df.to_sql("sales", conn, if_exists="replace", index=False)

720

In [22]:
buyers_df.to_sql("buyers", conn, if_exists="replace", index=False)

20000

PROPERTY & PRICING ANALYSIS

Q1 . What is the average listing price by city?

In [23]:
query = """
SELECT city, AVG(price) AS avg_price
FROM listings
GROUP BY city;
"""

df_avg_price_city = pd.read_sql(query, conn)
print(df_avg_price_city)

          City     avg_price
0      Chicago  2.430678e+06
1      Houston  2.436811e+06
2  Los Angeles  2.442418e+06
3     New York  2.493320e+06
4      Phoenix  2.459962e+06

In [24]:
query = """
SELECT CITY, COUNT(*) as total_listings
FROM listings
GROUP BY CITY;
"""

df_city_listings = pd.read_sql(query, conn)
print(df_city_listings)

          City  total_listings
0      Chicago            4293
1      Houston            4091
2  Los Angeles            4318
3     New York            4269
4      Phoenix            4229

Q2 . What is the average price per square foot by property type?

In [27]:
query = """
SELECT Property_Type AS property_type,
    AVG(Price * 1.0 / Sqft) AS avg_price_per_sqft
FROM listings
WHERE Sqft IS NOT NULL
  AND Sqft > 0
GROUP BY Property_Type
ORDER BY avg_price_per_sqft DESC;
"""

df_avg_price_per_sqft = pd.read_sql(query, conn)
print(df_avg_price_per_sqft)

  property_type  avg_price_per_sqft
0         House          796.040653
1     Apartment          792.203348
2     Townhouse          789.745399
3         Condo          754.675722

Q3 . How does furnishing status impact property prices?

In [30]:
query = """
SELECT pa.furnishing_status, COUNT(*) AS total_properties,
ROUND(AVG(l.Price), 2) AS avg_price,
ROUND(MIN(l.Price), 2) AS min_price,
ROUND(MAX(l.Price), 2) AS max_price
FROM property_attributes pa
JOIN listings l
  ON pa.listing_id = l.Listing_ID
WHERE pa.furnishing_status IS NOT NULL
GROUP BY pa.furnishing_status
ORDER BY avg_price DESC;
"""

df_total_properties = pd.read_sql(query, conn)
print(df_total_properties)

  furnishing_status  total_properties   avg_price  min_price   max_price
0         Furnished              6977  2463539.06  100082.01  4997593.10
1    Semi-Furnished              7013  2461192.65  100027.13  4999863.52
2       Unfurnished              7210  2433975.10  100458.61  4998967.92

In [7]:
conn = sqlite3.connect("brickview_realstate.db")
cursor = conn.cursor()

Q4 . Do properties closer to metro stations command higher prices?

In [3]:
query = """
SELECT
    CASE
        WHEN metro_distance_km IS NOT NULL AND metro_distance_km * 1000 <= 500 THEN '0-500 meters'
        WHEN metro_distance_km IS NOT NULL AND metro_distance_km * 1000 <= 1000 THEN '501-1000 meters'
        WHEN metro_distance_km IS NOT NULL AND metro_distance_km * 1000 <= 2000 THEN '1001-2000 meters'
        ELSE '2000M+'
    END AS distance_band,
    COUNT(*) AS property_count,
    ROUND(AVG(l.price), 2) AS avg_price,
    ROUND(MIN(l.price), 2) AS min_price,
    ROUND(MAX(l.price), 2) AS max_price
FROM property_attributes pa
JOIN listings l
    ON pa.listing_id = l.listings_id
GROUP BY distance_band
ORDER BY avg_price DESC;
"""

query = query.replace("l.listings_id", "l.Listing_ID")
df_avg_price = pd.read_sql(query, conn)
print(df_avg_price)

      distance_band  property_count   avg_price  min_price   max_price
0            2000M+           18292  2464613.02  100027.13  4999863.52
1      0-500 meters             611  2424531.90  116086.31  4987389.26
2  1001-2000 meters            1507  2369435.61  101180.33  4987047.72
3   501-1000 meters             790  2357704.84  101767.99  4997111.88

Q5 . Are rented properties priced differently from non-rented ones?

In [12]:
query = """
SELECT 
    CASE 
        WHEN is_rented = 1 THEN 'Rented'
        ELSE 'Not Rented'
    END AS rental_status,
    COUNT(*) AS property_count,
    AVG(price) AS avg_price,
    MIN(price) AS min_price,
    MAX(price) AS max_price
FROM property_attributes pa
JOIN listings l ON pa.listing_id = l.Listing_ID
GROUP BY rental_status;
"""
query = query.replace("l.listings_id", "l.Listing_ID")
df_rental_status = pd.read_sql(query, conn)
print(df_rental_status)

  rental_status  property_count     avg_price  min_price   max_price
0    Not Rented           10622  2.448250e+06  100027.13  4999463.77
1        Rented           10578  2.457185e+06  100082.01  4999863.52

Q6 . How do bedrooms and bathrooms affect pricing?

In [21]:
query = """
SELECT
    pa.bedrooms,
    pa.bathrooms,
    COUNT(*) AS property_count,
    AVG(l.price) AS avg_price,
    MIN(l.price) AS min_price,
    MAX(l.price) AS max_price
FROM property_attributes pa
JOIN listings l
    ON pa.listing_id = l.Listing_ID
GROUP BY pa.bedrooms, bathrooms
ORDER BY pa.bedrooms, bathrooms;
"""
query = query.replace("l.listings_id", "l.Listing_ID")
df_bedrooms_bathrooms = pd.read_sql(query, conn)
print(df_bedrooms_bathrooms)

    bedrooms  bathrooms  property_count     avg_price      min_price  \
0          1          1            1040  2.434001e+06  102914.310000
1          1          2            1047  2.509475e+06  106349.810000
2          1          3            1028  2.459033e+06  100613.180000
3          1          4            1094  2.455533e+06  103179.460000
4          2          1            1068  2.455735e+06  103066.003828
5          2          2            1127  2.378688e+06  109084.390000
6          2          3            1060  2.482619e+06  110132.995219
7          2          4            1021  2.555766e+06  108618.983283
8          3          1            1032  2.426008e+06  103991.620000
9          3          2            1064  2.409123e+06  103003.180000
10         3          3            1030  2.455024e+06  110584.510000
11         3          4            1068  2.478881e+06  100330.740000
12         4          1            1080  2.434956e+06  104320.460000
13         4          2            1037  2.450750e+06  107067.020000
14         4          3            1034  2.393515e+06  100082.010000
15         4          4            1118  2.471536e+06  114191.981728
16         5          1            1095  2.384940e+06  100458.610000
17         5          2            1066  2.478068e+06  101201.920000
18         5          3            1066  2.424067e+06  100027.130000
19         5          4            1025  2.527192e+06  100478.090000

     max_price
0   4991616.90
1   4999463.77
2   4992521.05
3   4998032.07
4   4989814.26
5   4995504.67
6   4987908.19
7   4998967.92
8   4986875.58
9   4998508.49
10  4999863.52
11  4996278.84
12  4992631.99
13  4997593.10
14  4997111.88
15  4996416.56
16  4994023.99
17  4998516.33
18  4998687.21
19  4995869.83

Q7 . Do properties with parking and power backup sell at higher prices?

In [15]:
query = """
SELECT
    CASE
        WHEN parking_Available = 'True' AND power_backup = 'True' THEN 'parking_Availabe & power backup'
        WHEN parking_Available = 'True' AND power_backup = 'False' THEN 'parking_Available only'
        WHEN parking_Available = 'False' AND power_backup = 'True' THEN 'power_backup only'
        ELSE 'Neither'
    END AS amenities,
    COUNT(*) AS property_count,
    AVG(price) AS avg_price,
    MIN(price) AS min_price,
    MAX(price) AS max_price
FROM property_attributes pa
JOIN listings l ON pa.listing_id = l.Listing_ID
GROUP BY
    CASE
        WHEN parking_Available = 'True' AND power_backup = 'True' THEN 'parking_Available & power backup'
        WHEN parking_Available = 'True' AND power_backup = 'False' THEN 'parking_Available only'
        WHEN parking_Available = 'False' AND power_backup = 'True' THEN 'power_backup only'
        ELSE 'Neither'
    END
ORDER BY avg_price DESC;
"""

df_avg_price = pd.read_sql(query, conn)
print(df_avg_price)

  amenities  property_count     avg_price  min_price   max_price
0   Neither           21200  2.452708e+06  100027.13  4999863.52

Q8 . How does year built influence listing price?

In [ ]:
import sqlite3

conn = sqlite3.connect("brickview_realstate.db")

query = """
SELECT
    CASE
        WHEN year_built >= 2020 THEN '2020-present'
        WHEN year_built >= 2010 THEN '2010-2019'
        WHEN year_built >= 2000 THEN '2000-2009'
        WHEN year_built >= 1990 THEN '1990-1999'
        ELSE 'Before 1990'
    END AS construction_period,
    COUNT(*) AS property_count,
    AVG(l.price) AS avg_listing_price,
    MIN(l.price) AS min_price,
    MAX(l.price) AS max_price
FROM property_attributes pa
JOIN listings l ON pa.listing_id = l.Listing_ID
GROUP BY
    CASE
        WHEN year_built >= 2020 THEN '2020-present'
        WHEN year_built >= 2010 THEN '2010-2019'
        WHEN year_built >= 2000 THEN '2000-2009'
        WHEN year_built >= 1990 THEN '1990-1999'
        ELSE 'Before 1990'
    END
ORDER BY avg_listing_price DESC;
"""

query = query.replace("l.listings_id", "l.Listing_ID")
df_avg_listing_price = pd.read_sql(query, conn)
print(df_avg_listing_price)

  construction_period  property_count  avg_listing_price  min_price  \
0           1990-1999            6081       2.507602e+06  100458.61
1        2020-present            2598       2.475700e+06  100330.74
2           2000-2009            6154       2.434915e+06  100082.01
3           2010-2019            6367       2.408097e+06  100027.13

    max_price
0  4999463.77
1  4998516.33
2  4998687.21
3  4999863.52

Q9 . Which cities have the highest average property prices?

In [7]:
query = """
SELECT
    city,
    COUNT(*) AS property_count,
    AVG(price) AS avg_price,
    MIN(price) AS min_price,
    MAX(price) AS max_price
FROM listings
GROUP BY city
ORDER BY avg_price DESC;
"""

df_avg_price = pd.read_sql(query, conn)
print(df_avg_price)

          City  property_count     avg_price  min_price   max_price
0     New York            4269  2.493320e+06  100027.13  4998508.49
1      Phoenix            4229  2.459962e+06  100458.61  4999863.52
2  Los Angeles            4318  2.442418e+06  100613.18  4999463.77
3      Houston            4091  2.436811e+06  100882.19  4998687.21
4      Chicago            4293  2.430678e+06  100082.01  4997593.10

Q10 . How are properties distributed across price buckets?

In [3]:
query = """
SELECT
    CASE
        WHEN Price < 100000 THEN 'Below 100k'
        WHEN Price BETWEEN 100000 AND 299999 THEN '100K - 299K'
        WHEN Price BETWEEN 300000 AND 499999 THEN '300K - 499K'
        WHEN Price BETWEEN 500000 AND 999999 THEN '500K - 999K'
        ELSE '1M and Above'
    END AS price_bucket,
    COUNT(*) AS Property_count,
    AVG(price) AS avg_price,
    MIN(price) AS min_price
FROM listings
GROUP BY price_bucket
ORDER BY min_price;
"""

df_min_price = pd.read_sql(query, conn)
print(df_min_price)

   price_bucket  Property_count     avg_price   min_price
0   100K - 299K             922  2.022725e+05   100027.13
1   300K - 499K             945  4.009215e+05   300379.04
2   500K - 999K            2402  7.480466e+05   500242.12
3  1M and Above           16931  2.931619e+06  1000322.88

SALES & MARKET PERFORMANCE

Q11 . What is the average days on market by city?

In [10]:
import pandas as pd
import sqlite3

query = """
SELECT
    l.city AS City,
    AVG(s.days_on_market) AS avg_days_on_market
FROM listings l
JOIN sales s
    ON l.Listing_ID = s.listing_id
GROUP BY l.city
ORDER BY avg_days_on_market DESC;
"""

conn = sqlite3.connect("brickview_realstate.db")
df_avg_days_on_market = pd.read_sql(query, conn)
print(df_avg_days_on_market)

          City  avg_days_on_market
0  Los Angeles           65.126408
1      Chicago           64.250577
2     New York           60.847639
3      Phoenix           59.654343
4      Houston           58.511086

Q12 . Which property types sell the fastest?

In [3]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("brickview_realstate.db")

query = """
SELECT 
    l.Listing_ID AS property_id,
    l.City,
    ROUND(l.Date_Listed) AS days_on_market
FROM listings l
JOIN sales s
    ON l.Listing_ID = s.listing_id
ORDER BY days_on_market ASC;
"""

df_DATEDIFF = pd.read_sql(query, conn)
print(df_DATEDIFF)

    property_id         City  days_on_market
0        L00001     New York          2023.0
1        L00003      Houston          2023.0
2        L00006     New York          2023.0
3        L00007  Los Angeles          2023.0
4        L00008      Houston          2023.0
..          ...          ...             ...
715      L01167     New York          2024.0
716      L01170      Chicago          2024.0
717      L01178      Houston          2024.0
718      L01186     New York          2024.0
719      L01196      Chicago          2024.0

[720 rows x 3 columns]

Q13 . What percentage of properties are sold above listing price?

In [6]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("brickview_realstate.db")

query = """
SELECT
    ROUND(
        100.0 * SUM(CASE WHEN s.Sale_Price > l.price THEN 1 ELSE 0 END)
        / COUNT(*),
        2
    ) AS percentage_sold_above_listing
FROM sales s
JOIN listings l
    ON s.listing_id = l.Listing_ID
WHERE s.Sale_Price IS NOT NULL
  AND l.price IS NOT NULL;
"""

df_Price = pd.read_sql(query, conn)
print(df_Price)

   percentage_sold_above_listing
0                          49.31

Q14 . What is the sale-to-list price ratio by city?

In [3]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("brickview_realstate.db")

query = """
SELECT
  l.city AS City,
  ROUND(AVG((s.sale_price * 100.0) / l.price), 2) AS sale_to_list_ratio_pct
FROM sales s
JOIN listings l
  ON s.listing_id = l.Listing_ID
WHERE s.sale_price IS NOT NULL
  AND l.price IS NOT NULL
  AND l.price > 0
GROUP BY l.city
ORDER BY sale_to_list_ratio_pct DESC;
"""
df_sale_to_list_ratio_pct = pd.read_sql(query, conn)
print(df_sale_to_list_ratio_pct)

          City  sale_to_list_ratio_pct
0      Chicago                  100.15
1      Houston                  100.00
2  Los Angeles                   99.98
3     New York                   99.96
4      Phoenix                   99.89

Q15 . Which listings took more than 90 days to sell?

In [7]:
cols = [row[1] for row in conn.execute("PRAGMA table_info(listings)").fetchall()]

can_compute_days = ("Date_Sold" in cols) and ("Date_Listed" in cols)
has_days_col = "Days_on_Market" in cols

select_parts = []
# Property_Type
select_parts.append("Property_Type" if "Property_Type" in cols else "NULL AS Property_Type")
# Listing_ID -> listing_id
select_parts.append("Listing_ID AS listing_id" if "Listing_ID" in cols else "NULL AS listing_id")
# City
select_parts.append("City" if "City" in cols else "NULL AS City")
# Date_Listed
select_parts.append("Date_Listed" if "Date_Listed" in cols else "NULL AS Date_Listed")
# Date_Sold
select_parts.append("Date_Sold" if "Date_Sold" in cols else "NULL AS Date_Sold")
# Days_on_Market: use existing column, or compute from dates, or NULL
if has_days_col:
    select_parts.append("Days_on_Market")
elif can_compute_days:
    select_parts.append("ROUND(julianday(Date_Sold) - julianday(Date_Listed)) AS Days_on_Market")
else:
    select_parts.append("NULL AS Days_on_Market")

select_clause = ",\n    ".join(select_parts)

# Build WHERE / ORDER clauses depending on availability
if has_days_col:
    where_clause = "WHERE Days_on_Market > 90"
    order_clause = "ORDER BY Days_on_Market DESC"
elif can_compute_days:
    where_clause = "WHERE (julianday(Date_Sold) - julianday(Date_Listed)) > 90"
    order_clause = "ORDER BY Days_on_Market DESC"
else:
    where_clause = ""  # cannot filter by days on market
    order_clause = ""

query = f"""
SELECT
    {select_clause}
FROM listings
{where_clause}
{order_clause};
"""

df_Days_on_Market = pd.read_sql(query, conn)
print(df_Days_on_Market)

      Property_Type listing_id         City Date_Listed Date_Sold  \
0         Apartment     L00001     New York  2023-05-06      None
1         Apartment     L00002  Los Angeles  2023-02-14      None
2         Apartment     L00003      Houston  2023-04-22      None
3         Apartment     L00004      Phoenix  2024-01-02      None
4         Townhouse     L00005      Phoenix  2023-10-29      None
...             ...        ...          ...         ...       ...
21195         House     L21196      Phoenix  2023-12-31      None
21196         Condo     L21197      Phoenix  2023-07-23      None
21197     Apartment     L21198  Los Angeles  2024-06-30      None
21198     Townhouse     L21199  Los Angeles  2023-09-17      None
21199     Apartment     L21200     New York  2023-07-28      None

      Days_on_Market
0               None
1               None
2               None
3               None
4               None
...              ...
21195           None
21196           None
21197           None
21198           None
21199           None

[21200 rows x 6 columns]

Q16 . How does metro distance affect time on market?

In [5]:
cursor = conn.cursor()
sales_cols = [r[1] for r in cursor.execute("PRAGMA table_info(sales)").fetchall()]
listing_cols = [r[1] for r in cursor.execute("PRAGMA table_info(listings)").fetchall()]

# find sale date column in sales table
for c in ['sale_date','Sale_Date','Date_Sold','date_sold','saleDate','SaleDate']:
    if c in sales_cols:
        sale_date_col = c
        break
else:
    raise RuntimeError(f"Could not find sale date column in sales table. Found: {', '.join(sales_cols)}")

# find listing date column in listings table
for c in ['Date_Listed','date_listed','listed_date','DateListed','dateListed']:
    if c in listing_cols:
        listing_date_col = c
        break
else:
    raise RuntimeError(f"Could not find listing date column in listings table. Found: {', '.join(listing_cols)}")

# find listing id column name used in listings table
for c in ['Listing_ID','listing_id','ListingId','listingId']:
    if c in listing_cols:
        listing_id_col = c
        break
else:
    raise RuntimeError(f"Could not find listing id column in listings table. Found: {', '.join(listing_cols)}")

# Build and run query using the detected column names (quoted to preserve case)
query = f"""
SELECT
    CASE
        WHEN pa.metro_distance_km < 1 THEN '0-1 km'
        WHEN pa.metro_distance_km < 3 THEN '1-3 km'
        WHEN pa.metro_distance_km < 5 THEN '3-5 km'
        ELSE '5+ km'
    END AS metro_distance_km,
    ROUND(AVG(julianday(s.\"{sale_date_col}\") - julianday(l.\"{listing_date_col}\")), 2) AS avg_Days_on_Market,
    COUNT(*) AS total_listings
FROM listings l
JOIN property_attributes pa ON pa.listing_id = l.\"{listing_id_col}\"
JOIN sales s ON s.listing_id = l.\"{listing_id_col}\"
WHERE pa.metro_distance_km IS NOT NULL
  AND s.\"{sale_date_col}\" IS NOT NULL
  AND l.\"{listing_date_col}\" IS NOT NULL
GROUP BY
    CASE
        WHEN pa.metro_distance_km < 1 THEN '0-1 km'
        WHEN pa.metro_distance_km < 3 THEN '1-3 km'
        WHEN pa.metro_distance_km < 5 THEN '3-5 km'
        ELSE '5+ km'
    END
ORDER BY avg_Days_on_Market;
"""

df_Days_on_Market = pd.read_sql(query, conn)
print(df_Days_on_Market)

  metro_distance_km  avg_Days_on_Market  total_listings
0            3-5 km               59.72             186
1             5+ km               60.75             302
2            1-3 km               63.96             165
3            0-1 km               65.30              67

Q17 . What is the monthly sales trend?

In [12]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("brickview_realstate.db")

query = """
SELECT
    CAST(strftime('%Y', Date_Sold) AS INTEGER) AS sale_year,
    CAST(strftime('%m', Date_Sold) AS INTEGER) AS sale_month,
    COUNT(*) AS properties_sold,
    SUM(Sale_Price) AS total_sales_value,
    AVG(Sale_Price) AS average_sale_price
FROM sales
WHERE Date_Sold IS NOT NULL
GROUP BY
    sale_year,
    sale_month
ORDER BY
    sale_year,
    sale_month;
"""

df_sale_year_sale_month = pd.read_sql(query, conn)
print(df_sale_year_sale_month)

    sale_year  sale_month  properties_sold  total_sales_value  \
0        2023           1                7       5.298401e+06
1        2023           2               17       1.594507e+07
2        2023           3               20       1.999507e+07
3        2023           4               36       4.420825e+07
4        2023           5               45       5.138567e+07
5        2023           6               31       2.964344e+07
6        2023           7               48       5.600021e+07
7        2023           8               50       5.505066e+07
8        2023           9               46       4.986870e+07
9        2023          10               64       7.020253e+07
10       2023          11               46       4.997119e+07
11       2023          12               42       4.579371e+07
12       2024           1               44       4.800911e+07
13       2024           2               44       4.963750e+07
14       2024           3               39       4.139912e+07
15       2024           4               29       3.006874e+07
16       2024           5               45       4.518732e+07
17       2024           6               29       2.949840e+07
18       2024           7               24       2.561708e+07
19       2024           8               13       1.282358e+07
20       2024           9                1       2.293040e+05

    average_sale_price
0         7.569144e+05
1         9.379453e+05
2         9.997533e+05
3         1.228007e+06
4         1.141904e+06
5         9.562401e+05
6         1.166671e+06
7         1.101013e+06
8         1.084102e+06
9         1.096915e+06
10        1.086330e+06
11        1.090327e+06
12        1.091116e+06
13        1.128125e+06
14        1.061516e+06
15        1.036853e+06
16        1.004163e+06
17        1.017186e+06
18        1.067378e+06
19        9.864294e+05
20        2.293040e+05

Q18 . Which properties are currently unsold?

In [7]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("brickview_realstate.db")

query = """
SELECT
    Property_Type,
    address,
    City,
    Date_Listed,
    listing_price
FROM listings
WHERE Date_Sold IS NULL
ORDER BY Date_Listed DESC;
"""

cols = [r[1] for r in conn.execute("PRAGMA table_info(listings)").fetchall()]

def find(cands):
    for c in cands:
        if c in cols:
            return c
    return None

pt_col = find(['Property_Type','property_type','PropertyType'])
addr_col = find(['address','Address','addr'])
city_col = find(['City','city'])
date_listed_col = find(['Date_Listed','listed_date','DateListed','listedDate','listeddate'])
price_col = find(['listing_price','price','Listing_Price','listingPrice'])
date_sold_col = find(['Date_Sold','date_sold','DateSold','datesold'])

select_parts = [
    (f"{pt_col} AS Property_Type" if pt_col else "NULL AS Property_Type"),
    (f"{addr_col} AS address" if addr_col else "NULL AS address"),
    (f"{city_col} AS City" if city_col else "NULL AS City"),
    (f"{date_listed_col} AS Date_Listed" if date_listed_col else "NULL AS Date_Listed"),
    (f"{price_col} AS listing_price" if price_col else "NULL AS listing_price"),
]

where_clause = f"WHERE {date_sold_col} IS NULL" if date_sold_col else ""
order_clause = f"ORDER BY {date_listed_col} DESC" if date_listed_col else ""

# build the joiner separately to avoid backslashes inside f-string expressions
joiner = ",\n    "
query_corrected = f"SELECT\n    {joiner.join(select_parts)}\nFROM listings\n{where_clause}\n{order_clause};"

df_Date_Listed = pd.read_sql(query_corrected, conn)
print(df_Date_Listed)

      Property_Type address         City Date_Listed listing_price
0         Townhouse    None      Chicago  2024-12-31          None
1             Condo    None      Chicago  2024-12-31          None
2         Apartment    None      Phoenix  2024-12-31          None
3         Townhouse    None      Phoenix  2024-12-31          None
4             Condo    None      Houston  2024-12-31          None
...             ...     ...          ...         ...           ...
21195     Townhouse    None      Houston  2023-01-01          None
21196         Condo    None     New York  2023-01-01          None
21197         House    None      Chicago  2023-01-01          None
21198         House    None  Los Angeles  2023-01-01          None
21199     Apartment    None      Phoenix  2023-01-01          None

[21200 rows x 5 columns]

Q19 . Which agents have closed the most sales?

In [8]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("brickview_realstate.db")

query = """
SELECT
    agent_id,
    agent_name,
    COUNT(*) AS total_sales_closed
FROM agents
WHERE Date_Sold IS NOT NULL
GROUP BY
    agent_id,
    agent_name
ORDER BY deals_closed DESC;
"""
df_deals_closed = pd.read_sql(query_corrected, conn)
print(df_deals_closed)

      Property_Type address         City Date_Listed listing_price
0         Townhouse    None      Chicago  2024-12-31          None
1             Condo    None      Chicago  2024-12-31          None
2         Apartment    None      Phoenix  2024-12-31          None
3         Townhouse    None      Phoenix  2024-12-31          None
4             Condo    None      Houston  2024-12-31          None
...             ...     ...          ...         ...           ...
21195     Townhouse    None      Houston  2023-01-01          None
21196         Condo    None     New York  2023-01-01          None
21197         House    None      Chicago  2023-01-01          None
21198         House    None  Los Angeles  2023-01-01          None
21199     Apartment    None      Phoenix  2023-01-01          None

[21200 rows x 5 columns]

Q20 . Who are the top agents by total sales revenue?

In [7]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("brickview_realstate.db")

query = """
SELECT
    agent_id,
    agent_name,
    SUM(sale_price) AS total_sales_revenue,
    COUNT(*) AS properties_sold,
    AVG(sale_price) AS average_sale_price
FROM listings
WHERE Date_Sold IS NOT NULL
GROUP BY
    agent_id,
    agent_name
ORDER BY total_sales_revenue DESC;
"""
# build a robust query using actual table column names
listings_cols = [r[1] for r in conn.execute("PRAGMA table_info(listings)").fetchall()]
sales_cols = [r[1] for r in conn.execute("PRAGMA table_info(sales)").fetchall()]
agents_cols = [r[1] for r in conn.execute("PRAGMA table_info(agents)").fetchall()]

def find(cols, candidates):
    for c in candidates:
        if c in cols:
            return c
    return None

listing_id_col = find(listings_cols, ['Listing_ID','listing_id','ListingId','listingId'])
listing_agent_col = find(listings_cols, ['Agent_ID','agent_id','AgentId','agentId'])
sales_listing_id_col = find(sales_cols, ['listing_id','Listing_ID','ListingId'])
sales_price_col = find(sales_cols, ['sale_price','Sale_Price','SalePrice','salePrice'])
sales_date_col = find(sales_cols, ['Date_Sold','date_sold','Sale_Date','sale_date'])
agents_id_col = find(agents_cols, ['agents_id','agent_id','id','Agents_ID','Agent_ID'])
agents_name_col = find(agents_cols, ['name','agent_name','Name','Agent_Name'])

if not listing_agent_col:
    raise RuntimeError(f"Could not find agent id column in listings. Found: {listings_cols}")

# prepare joins / selects depending on availability of agents table / name
if agents_name_col and agents_id_col:
    join_agents = f'LEFT JOIN agents a ON a."{agents_id_col}" = l."{listing_agent_col}"'
    select_agent_name = f'a."{agents_name_col}" AS agent_name'
    group_by_extra = f', a."{agents_name_col}"'
else:
    join_agents = ''
    select_agent_name = 'NULL AS agent_name'
    group_by_extra = ''

# ensure sales columns exist
if not sales_listing_id_col or not sales_price_col:
    raise RuntimeError(f"Could not find required columns in sales table. Found: {sales_cols}")

# filter by sale date if available
where_clause = f'WHERE s."{sales_date_col}" IS NOT NULL' if sales_date_col else ''

query = f'''
SELECT
    l."{listing_agent_col}" AS agent_id,
    {select_agent_name},
    SUM(s."{sales_price_col}") AS total_sales_revenue,
    COUNT(*) AS properties_sold,
    AVG(s."{sales_price_col}") AS average_sale_price
FROM listings l
JOIN sales s ON s."{sales_listing_id_col}" = l."{listing_id_col}"
{join_agents}
{where_clause}
GROUP BY
    l."{listing_agent_col}"{group_by_extra}
ORDER BY total_sales_revenue DESC;
'''

df_total_sales_revenue = pd.read_sql(query, conn)
print(df_total_sales_revenue)

   agent_id   agent_name  total_sales_revenue  properties_sold  \
0     A0011  Agent A0011         2.788227e+07               24
1     A0042  Agent A0042         2.719161e+07               25
2     A0043  Agent A0043         2.410242e+07               20
3     A0035  Agent A0035         2.272575e+07               21
4     A0014  Agent A0014         2.203401e+07               21
5     A0046  Agent A0046         2.133580e+07               20
6     A0048  Agent A0048         2.118631e+07               19
7     A0027  Agent A0027         2.109970e+07               18
8     A0009  Agent A0009         2.027927e+07               17
9     A0029  Agent A0029         1.958650e+07               18
10    A0039  Agent A0039         1.922301e+07               16
11    A0036  Agent A0036         1.920954e+07               16
12    A0050  Agent A0050         1.896855e+07               17
13    A0025  Agent A0025         1.881859e+07               17
14    A0017  Agent A0017         1.858385e+07               14
15    A0007  Agent A0007         1.841448e+07               19
16    A0001  Agent A0001         1.817392e+07               15
17    A0015  Agent A0015         1.775286e+07               16
18    A0019  Agent A0019         1.673061e+07               17
19    A0021  Agent A0021         1.654831e+07               17
20    A0006  Agent A0006         1.652323e+07               15
21    A0031  Agent A0031         1.572329e+07               13
22    A0003  Agent A0003         1.558495e+07               16
23    A0018  Agent A0018         1.553988e+07               13
24    A0012  Agent A0012         1.473053e+07               11
25    A0023  Agent A0023         1.463487e+07               12
26    A0010  Agent A0010         1.422816e+07               15
27    A0033  Agent A0033         1.420215e+07               16
28    A0041  Agent A0041         1.407748e+07               15
29    A0049  Agent A0049         1.395495e+07               10
30    A0047  Agent A0047         1.347818e+07               14
31    A0016  Agent A0016         1.345035e+07               15
32    A0024  Agent A0024         1.319602e+07               14
33    A0004  Agent A0004         1.275477e+07               11
34    A0030  Agent A0030         1.248445e+07               11
35    A0037  Agent A0037         1.231499e+07               12
36    A0040  Agent A0040         1.203929e+07               13
37    A0045  Agent A0045         1.181907e+07               13
38    A0002  Agent A0002         1.175497e+07                8
39    A0008  Agent A0008         1.107190e+07               11
40    A0038  Agent A0038         1.106064e+07               12
41    A0032  Agent A0032         1.065332e+07               10
42    A0044  Agent A0044         1.024755e+07                8
43    A0005  Agent A0005         1.011439e+07               10
44    A0028  Agent A0028         9.831891e+06               10
45    A0020  Agent A0020         9.605503e+06               10
46    A0013  Agent A0013         9.114420e+06                7
47    A0026  Agent A0026         8.479518e+06               12
48    A0034  Agent A0034         7.011394e+06                7
49    A0022  Agent A0022         6.303601e+06                9

    average_sale_price
0         1.161761e+06
1         1.087664e+06
2         1.205121e+06
3         1.082179e+06
4         1.049238e+06
5         1.066790e+06
6         1.115069e+06
7         1.172205e+06
8         1.192899e+06
9         1.088139e+06
10        1.201438e+06
11        1.200596e+06
12        1.115797e+06
13        1.106976e+06
14        1.327418e+06
15        9.691832e+05
16        1.211595e+06
17        1.109554e+06
18        9.841536e+05
19        9.734299e+05
20        1.101549e+06
21        1.209484e+06
22        9.740596e+05
23        1.195375e+06
24        1.339140e+06
25        1.219573e+06
26        9.485443e+05
27        8.876343e+05
28        9.384988e+05
29        1.395495e+06
30        9.627273e+05
31        8.966901e+05
32        9.425727e+05
33        1.159524e+06
34        1.134950e+06
35        1.026249e+06
36        9.260991e+05
37        9.091594e+05
38        1.469371e+06
39        1.006536e+06
40        9.217198e+05
41        1.065332e+06
42        1.280944e+06
43        1.011439e+06
44        9.831891e+05
45        9.605503e+05
46        1.302060e+06
47        7.066265e+05
48        1.001628e+06
49        7.004001e+05

Q21 . Which agents close deals fastest?

In [9]:
query = """
SELECT
    a.Agent_ID AS agent_id,
    a.Name AS agent_name,
    ROUND(AVG(julianday(s.Date_Sold) - julianday(l.Date_Listed)), 2) AS avg_days_to_close,
    COUNT(s.Listing_ID) AS deals_closed
FROM agents a
JOIN listings l ON l.Agent_ID = a.Agent_ID
JOIN sales s ON s.Listing_ID = l.Listing_ID
WHERE s.Date_Sold IS NOT NULL
  AND l.Date_Listed IS NOT NULL
GROUP BY
    a.Agent_ID,
    a.Name
ORDER BY
    avg_days_to_close ASC;
"""

df_agents_closing_speed = pd.read_sql(query, conn)
print(df_agents_closing_speed)

   agent_id   agent_name  avg_days_to_close  deals_closed
0     A0044  Agent A0044              36.88             8
1     A0013  Agent A0013              42.43             7
2     A0037  Agent A0037              44.50            12
3     A0002  Agent A0002              45.50             8
4     A0008  Agent A0008              46.64            11
5     A0017  Agent A0017              48.57            14
6     A0026  Agent A0026              49.50            12
7     A0012  Agent A0012              50.64            11
8     A0010  Agent A0010              51.13            15
9     A0043  Agent A0043              52.35            20
10    A0009  Agent A0009              52.71            17
11    A0018  Agent A0018              54.69            13
12    A0022  Agent A0022              55.56             9
13    A0028  Agent A0028              55.60            10
14    A0040  Agent A0040              55.92            13
15    A0041  Agent A0041              56.13            15
16    A0036  Agent A0036              56.38            16
17    A0023  Agent A0023              56.50            12
18    A0046  Agent A0046              59.90            20
19    A0027  Agent A0027              61.33            18
20    A0047  Agent A0047              61.36            14
21    A0030  Agent A0030              61.55            11
22    A0049  Agent A0049              61.80            10
23    A0001  Agent A0001              61.93            15
24    A0019  Agent A0019              62.00            17
25    A0029  Agent A0029              62.00            18
26    A0024  Agent A0024              62.21            14
27    A0020  Agent A0020              62.30            10
28    A0032  Agent A0032              62.50            10
29    A0033  Agent A0033              62.75            16
30    A0050  Agent A0050              62.88            17
31    A0005  Agent A0005              63.90            10
32    A0007  Agent A0007              64.47            19
33    A0016  Agent A0016              64.53            15
34    A0011  Agent A0011              64.71            24
35    A0015  Agent A0015              65.94            16
36    A0042  Agent A0042              67.00            25
37    A0014  Agent A0014              67.24            21
38    A0035  Agent A0035              67.24            21
39    A0039  Agent A0039              67.50            16
40    A0021  Agent A0021              67.82            17
41    A0034  Agent A0034              68.29             7
42    A0048  Agent A0048              68.58            19
43    A0031  Agent A0031              68.62            13
44    A0045  Agent A0045              69.08            13
45    A0038  Agent A0038              70.33            12
46    A0025  Agent A0025              70.76            17
47    A0004  Agent A0004              80.09            11
48    A0003  Agent A0003              80.25            16
49    A0006  Agent A0006              81.33            15

Q22 . Does experience correlate with deals closed?

In [11]:
query = """
SELECT
    a."Agent_ID" AS agent_id,
    a."Name" AS agent_name,
    a."experience_years" AS years_experience,
    COUNT(s."Listing_ID") AS deals_closed
FROM agents a
LEFT JOIN listings l
    ON a."Agent_ID" = l."Agent_ID"
LEFT JOIN sales s
    ON l."Listing_ID" = s."Listing_ID"
WHERE s."Date_Sold" IS NOT NULL
GROUP BY
    a."Agent_ID",
    a."Name",
    a."experience_years"
ORDER BY
    a."experience_years" DESC;
"""

df_years_experience = pd.read_sql(query, conn)
print(df_years_experience)

   agent_id   agent_name  years_experience  deals_closed
0     A0019  Agent A0019                25            17
1     A0045  Agent A0045                25            13
2     A0011  Agent A0011                23            24
3     A0014  Agent A0014                23            21
4     A0036  Agent A0036                22            16
5     A0003  Agent A0003                21            16
6     A0021  Agent A0021                21            17
7     A0032  Agent A0032                21            10
8     A0039  Agent A0039                21            16
9     A0048  Agent A0048                21            19
10    A0002  Agent A0002                20             8
11    A0018  Agent A0018                20            13
12    A0020  Agent A0020                20            10
13    A0031  Agent A0031                20            13
14    A0043  Agent A0043                20            20
15    A0044  Agent A0044                20             8
16    A0017  Agent A0017                19            14
17    A0028  Agent A0028                19            10
18    A0008  Agent A0008                18            11
19    A0009  Agent A0009                18            17
20    A0023  Agent A0023                18            12
21    A0010  Agent A0010                17            15
22    A0026  Agent A0026                17            12
23    A0005  Agent A0005                16            10
24    A0012  Agent A0012                16            11
25    A0029  Agent A0029                16            18
26    A0047  Agent A0047                16            14
27    A0016  Agent A0016                15            15
28    A0037  Agent A0037                15            12
29    A0013  Agent A0013                14             7
30    A0025  Agent A0025                14            17
31    A0049  Agent A0049                14            10
32    A0022  Agent A0022                13             9
33    A0030  Agent A0030                13            11
34    A0042  Agent A0042                13            25
35    A0038  Agent A0038                12            12
36    A0050  Agent A0050                11            17
37    A0001  Agent A0001                10            15
38    A0046  Agent A0046                10            20
39    A0024  Agent A0024                 9            14
40    A0006  Agent A0006                 7            15
41    A0034  Agent A0034                 7             7
42    A0004  Agent A0004                 5            11
43    A0027  Agent A0027                 5            18
44    A0041  Agent A0041                 5            15
45    A0007  Agent A0007                 4            19
46    A0040  Agent A0040                 4            13
47    A0033  Agent A0033                 3            16
48    A0015  Agent A0015                 2            16
49    A0035  Agent A0035                 1            21

Q23 . Do agents with higher ratings close deals faster?

In [13]:
query = """
SELECT
    a."Agent_ID" AS agent_id,
    a."Name" AS agent_name,
    a.rating,
    ROUND(AVG(julianday(s."Date_Sold") - julianday(l."Date_Listed")), 2) AS avg_days_to_close,
    COUNT(s."Listing_ID") AS deals_closed
FROM agents a
JOIN listings l
    ON l."Agent_ID" = a."Agent_ID"
JOIN sales s
    ON s."Listing_ID" = l."Listing_ID"
WHERE s."Date_Sold" IS NOT NULL
  AND l."Date_Listed" IS NOT NULL
GROUP BY
    a."Agent_ID",
    a."Name",
    a.rating
ORDER BY
    avg_days_to_close ASC;
"""

df_days_to_close = pd.read_sql(query, conn)
print(df_days_to_close)

   agent_id   agent_name  rating  avg_days_to_close  deals_closed
0     A0044  Agent A0044     3.6              36.88             8
1     A0013  Agent A0013     4.8              42.43             7
2     A0037  Agent A0037     4.1              44.50            12
3     A0002  Agent A0002     3.8              45.50             8
4     A0008  Agent A0008     3.4              46.64            11
5     A0017  Agent A0017     4.3              48.57            14
6     A0026  Agent A0026     5.0              49.50            12
7     A0012  Agent A0012     3.5              50.64            11
8     A0010  Agent A0010     3.4              51.13            15
9     A0043  Agent A0043     3.2              52.35            20
10    A0009  Agent A0009     4.4              52.71            17
11    A0018  Agent A0018     4.1              54.69            13
12    A0022  Agent A0022     3.2              55.56             9
13    A0028  Agent A0028     4.0              55.60            10
14    A0040  Agent A0040     4.8              55.92            13
15    A0041  Agent A0041     3.6              56.13            15
16    A0036  Agent A0036     3.7              56.38            16
17    A0023  Agent A0023     4.1              56.50            12
18    A0046  Agent A0046     3.2              59.90            20
19    A0027  Agent A0027     4.6              61.33            18
20    A0047  Agent A0047     4.0              61.36            14
21    A0030  Agent A0030     3.3              61.55            11
22    A0049  Agent A0049     4.1              61.80            10
23    A0001  Agent A0001     4.3              61.93            15
24    A0019  Agent A0019     3.1              62.00            17
25    A0029  Agent A0029     4.8              62.00            18
26    A0024  Agent A0024     4.1              62.21            14
27    A0020  Agent A0020     5.0              62.30            10
28    A0032  Agent A0032     3.3              62.50            10
29    A0033  Agent A0033     3.1              62.75            16
30    A0050  Agent A0050     3.5              62.88            17
31    A0005  Agent A0005     4.3              63.90            10
32    A0007  Agent A0007     3.8              64.47            19
33    A0016  Agent A0016     4.8              64.53            15
34    A0011  Agent A0011     4.9              64.71            24
35    A0015  Agent A0015     4.1              65.94            16
36    A0042  Agent A0042     4.3              67.00            25
37    A0014  Agent A0014     3.7              67.24            21
38    A0035  Agent A0035     3.4              67.24            21
39    A0039  Agent A0039     3.5              67.50            16
40    A0021  Agent A0021     3.6              67.82            17
41    A0034  Agent A0034     3.1              68.29             7
42    A0048  Agent A0048     4.0              68.58            19
43    A0031  Agent A0031     3.6              68.62            13
44    A0045  Agent A0045     4.2              69.08            13
45    A0038  Agent A0038     4.3              70.33            12
46    A0025  Agent A0025     3.2              70.76            17
47    A0004  Agent A0004     4.5              80.09            11
48    A0003  Agent A0003     3.6              80.25            16
49    A0006  Agent A0006     4.9              81.33            15

Q24 . What is the average commission earned by each agent?

In [15]:
query = """
SELECT
    a."Agent_ID" AS agent_id,
    a."Name" AS agent_name,
    a."commission_rate" AS commission_rate,
    COUNT(s."Listing_ID") AS total_deals,
    ROUND(AVG(s."Sale_Price" * a."commission_rate" / 100), 2) AS avg_commission_earned,
    ROUND(SUM(s."Sale_Price" * a."commission_rate" / 100), 2) AS total_commission_earned
FROM agents a
LEFT JOIN listings l
    ON a."Agent_ID" = l."Agent_ID"
LEFT JOIN sales s
    ON l."Listing_ID" = s."Listing_ID"
WHERE s."Sale_Price" IS NOT NULL
GROUP BY
    a."Agent_ID",
    a."Name",
    a."commission_rate"
ORDER BY
    total_commission_earned DESC;
"""

df_comission_earned = pd.read_sql(query, conn)
print(df_comission_earned)

   agent_id   agent_name  commission_rate  total_deals  avg_commission_earned  \
0     A0035  Agent A0035             2.96           21               32032.49
1     A0042  Agent A0042             2.24           25               24363.68
2     A0009  Agent A0009             2.85           17               33997.61
3     A0011  Agent A0011             2.01           24               23351.40
4     A0050  Agent A0050             2.56           17               28564.40
5     A0029  Agent A0029             2.45           18               26659.40
6     A0019  Agent A0019             2.80           17               27556.30
7     A0021  Agent A0021             2.73           17               26574.64
8     A0003  Agent A0003             2.85           16               27760.70
9     A0014  Agent A0014             1.97           21               20670.00
10    A0043  Agent A0043             1.75           20               21089.62
11    A0018  Agent A0018             2.63           13               31438.36
12    A0027  Agent A0027             1.92           18               22506.34
13    A0017  Agent A0017             2.14           14               28406.74
14    A0031  Agent A0031             2.51           13               30358.05
15    A0024  Agent A0024             2.95           14               27805.90
16    A0025  Agent A0025             2.01           17               22250.22
17    A0033  Agent A0033             2.56           16               22723.44
18    A0001  Agent A0001             2.00           15               24231.89
19    A0012  Agent A0012             2.37           11               31737.61
20    A0030  Agent A0030             2.79           11               31665.09
21    A0046  Agent A0046             1.57           20               16748.61
22    A0036  Agent A0036             1.73           16               20770.32
23    A0007  Agent A0007             1.78           19               17251.46
24    A0010  Agent A0010             2.14           15               20298.85
25    A0045  Agent A0045             2.50           13               22728.98
26    A0048  Agent A0048             1.34           19               14941.92
27    A0023  Agent A0023             1.89           12               23049.93
28    A0032  Agent A0032             2.57           10               27379.03
29    A0015  Agent A0015             1.49           16               16532.35
30    A0039  Agent A0039             1.37           16               16459.71
31    A0006  Agent A0006             1.58           15               17404.47
32    A0002  Agent A0002             2.20            8               32326.16
33    A0020  Agent A0020             2.67           10               25646.69
34    A0049  Agent A0049             1.70           10               23723.41
35    A0028  Agent A0028             2.25           10               22121.75
36    A0047  Agent A0047             1.63           14               15692.45
37    A0037  Agent A0037             1.78           12               18267.24
38    A0004  Agent A0004             1.67           11               19364.05
39    A0016  Agent A0016             1.45           15               13002.01
40    A0008  Agent A0008             1.72           11               17312.42
41    A0040  Agent A0040             1.58           13               14632.37
42    A0041  Agent A0041             1.32           15               12388.18
43    A0034  Agent A0034             2.46            7               24640.04
44    A0013  Agent A0013             1.78            7               23176.67
45    A0044  Agent A0044             1.45            8               18573.68
46    A0026  Agent A0026             1.63           12               11518.01
47    A0038  Agent A0038             1.22           12               11244.98
48    A0022  Agent A0022             1.94            9               13587.76
49    A0005  Agent A0005             1.11           10               11226.97

    total_commission_earned
0                 672682.26
1                 609091.97
2                 577959.34
3                 560433.67
4                 485594.83
5                 479869.20
6                 468457.14
7                 451768.81
8                 444171.19
9                 434069.96
10                421792.32
11                408698.74
12                405114.18
13                397694.41
14                394654.65
15                389282.53
16                378253.68
17                363575.01
18                363478.40
19                349113.68
20                348316.02
21                334972.14
22                332325.11
23                327777.74
24                304482.71
25                295476.80
26                283896.50
27                276599.12
28                273790.32
29                264517.56
30                263355.29
31                261067.05
32                258609.25
33                256466.93
34                237234.07
35                221217.55
36                219694.37
37                219206.82
38                213004.59
39                195030.10
40                190436.63
41                190220.75
42                185822.76
43                172480.29
44                162236.68
45                148589.45
46                138216.14
47                134939.78
48                122289.86
49                112269.68

Q25 . Which agents currently have the most active listings?

In [7]:
import pandas as pd

listing_cols = [row[1] for row in conn.execute("PRAGMA table_info(listings)").fetchall()]
agents_cols = [row[1] for row in conn.execute("PRAGMA table_info(agents)").fetchall()]

def find_col(cols, candidates):
    for c in candidates:
        if c in cols:
            return c
    return None

status_col = find_col(listing_cols, ['status', 'Status', 'listing_status', 'Listing_Status'])
date_sold_col = find_col(listing_cols, ['Date_Sold', 'date_sold', 'Sale_Date', 'sale_date'])
listing_id_col = find_col(listing_cols, ['listing_id', 'Listing_ID', 'ListingId', 'listingId', 'listings_id', 'Listings_ID'])
listing_agent_col = find_col(listing_cols, ['agent_id', 'Agent_ID', 'AgentId', 'agentId'])
agents_id_col = find_col(agents_cols, ['agent_id', 'agents_id', 'Agent_ID', 'Agents_ID'])
agents_name_col = find_col(agents_cols, ['name', 'Name', 'agent_name', 'Agent_Name'])

sales_cols = [row[1] for row in conn.execute("PRAGMA table_info(sales)").fetchall()]
sales_listing_id_col = find_col(sales_cols, ['listing_id', 'Listing_ID', 'ListingId', 'listingId', 'listings_id', 'Listings_ID'])

if not agents_id_col:
    raise RuntimeError(f"Could not find agent id column in agents table. Found: {agents_cols}")
if not listing_agent_col:
    raise RuntimeError(f"Could not find agent id column in listings table. Found: {listing_cols}")
if not agents_name_col:
    raise RuntimeError(f"Could not find agent name column in agents table. Found: {agents_cols}")
if not listing_id_col:
    raise RuntimeError(f"Could not find listing id column in listings table. Found: {listing_cols}")

if status_col:
    where_clause = f"WHERE l.\"{status_col}\" = 'Active'"
elif date_sold_col:
    where_clause = f"WHERE l.\"{date_sold_col}\" IS NULL"
elif sales_listing_id_col:
    where_clause = f"""
WHERE l.\"{listing_id_col}\" NOT IN (
    SELECT s.\"{sales_listing_id_col}\"
    FROM sales s
    WHERE s.\"{sales_listing_id_col}\" IS NOT NULL
)
"""
else:
    raise RuntimeError(
        "Could not find a status or Date_Sold column in listings "
        "or a sales listing_id column to identify active listings."
    )

query = f"""
SELECT
    a."{agents_id_col}" AS agent_id,
    a."{agents_name_col}" AS agent_name,
    COUNT(l."{listing_id_col}") AS active_listings
FROM agents a
JOIN listings l
    ON a."{agents_id_col}" = l."{listing_agent_col}"
{where_clause}
GROUP BY
    a."{agents_id_col}",
    a."{agents_name_col}"
ORDER BY
    active_listings DESC;
"""

df_active_listings = pd.read_sql(query, conn)
print(df_active_listings)

   agent_id   agent_name  active_listings
0     A0023  Agent A0023              446
1     A0011  Agent A0011              439
2     A0008  Agent A0008              438
3     A0042  Agent A0042              435
4     A0014  Agent A0014              432
5     A0044  Agent A0044              430
6     A0020  Agent A0020              426
7     A0012  Agent A0012              425
8     A0015  Agent A0015              425
9     A0048  Agent A0048              425
10    A0016  Agent A0016              424
11    A0018  Agent A0018              422
12    A0031  Agent A0031              422
13    A0036  Agent A0036              422
14    A0033  Agent A0033              418
15    A0022  Agent A0022              417
16    A0040  Agent A0040              416
17    A0010  Agent A0010              415
18    A0027  Agent A0027              415
19    A0002  Agent A0002              414
20    A0037  Agent A0037              413
21    A0005  Agent A0005              412
22    A0026  Agent A0026              412
23    A0007  Agent A0007              411
24    A0035  Agent A0035              410
25    A0045  Agent A0045              410
26    A0009  Agent A0009              409
27    A0021  Agent A0021              409
28    A0050  Agent A0050              409
29    A0043  Agent A0043              408
30    A0028  Agent A0028              407
31    A0004  Agent A0004              406
32    A0032  Agent A0032              404
33    A0047  Agent A0047              404
34    A0006  Agent A0006              403
35    A0038  Agent A0038              401
36    A0041  Agent A0041              399
37    A0046  Agent A0046              397
38    A0030  Agent A0030              396
39    A0013  Agent A0013              395
40    A0029  Agent A0029              395
41    A0001  Agent A0001              392
42    A0017  Agent A0017              388
43    A0034  Agent A0034              388
44    A0049  Agent A0049              387
45    A0019  Agent A0019              386
46    A0025  Agent A0025              384
47    A0024  Agent A0024              380
48    A0039  Agent A0039              380
49    A0003  Agent A0003              379

 BUYER & FINANCING BEHAVIOR

Q26 . What percentage of buyers are investors vs end users?

In [8]:
query = """
SELECT
    buyer_type,
    COUNT(buyer_id) AS total_buyers,
    ROUND(
        COUNT(buyer_id) * 100.0 / (SELECT COUNT(*) FROM buyers),
        2
    ) AS percentage_of_buyers
FROM buyers
GROUP BY buyer_type;
"""

df_buyer_type = pd.read_sql(query, conn)
print(df_buyer_type)

  buyer_type  total_buyers  percentage_of_buyers
0   End User         10020                  50.1
1   Investor          9980                  49.9

Q27 . Which cities have the highest loan uptake rate?

In [9]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("brickview_realstate.db")

# discover column names to build a robust query (no 'loans' table expected)
def cols(table):
    return [r[1] for r in conn.execute(f"PRAGMA table_info({table})").fetchall()]

buyers_cols = cols("buyers")
sales_cols = cols("sales")
listing_cols = cols("listings")

def find(candidates, arr):
    for c in candidates:
        if c in arr:
            return c
    return None

buyer_id_col = find(['buyer_id','buyers_id','buyersId','Buyer_ID','buyers_id'], buyers_cols)
buyer_sale_id_col = find(['sale_id','sales_id','Sale_ID','saleId'], buyers_cols)
loan_taken_col = find(['loan_taken','loanTaken','loan_taken_flag'], buyers_cols)
loan_amount_col = find(['loan_amount','Loan_Amount','loanAmount'], buyers_cols)
buyer_city_col = find(['city','City','buyer_city','Buyer_City'], buyers_cols)

sales_id_col = find(['sales_id','sale_id','Sale_ID','id'], sales_cols)
sales_listing_id_col = find(['listing_id','Listing_ID','ListingId','listingId'], sales_cols)

listing_id_col = find(['listing_id','Listing_ID','ListingId','listingId','listings_id'], listing_cols)
listing_city_col = find(['city','City','town'], listing_cols)

# determine source of city
if listing_city_col and ((buyer_sale_id_col and sales_listing_id_col and listing_id_col) or (buyer_sale_id_col and sales_listing_id_col)):
    # join buyers -> sales -> listings to get city
    join_clause = []
    join_clause.append(f'LEFT JOIN sales s ON b."{buyer_sale_id_col}" = s."{sales_id_col}"' if buyer_sale_id_col and sales_id_col else '')
    join_clause.append(f'LEFT JOIN listings l ON s."{sales_listing_id_col}" = l."{listing_id_col}"' if sales_listing_id_col and listing_id_col else '')
    join_clause = "\n".join([j for j in join_clause if j])
    city_expr = f'l."{listing_city_col}"'
elif buyer_city_col:
    join_clause = ""
    city_expr = f'b."{buyer_city_col}"'
else:
    raise RuntimeError("Could not determine a city column from buyers or listings tables.")

# determine loan indicator expression
loan_indicator = None
if loan_taken_col:
    loan_indicator = f'(b."{loan_taken_col}" = 1 OR b."{loan_taken_col}" IN (\'True\',\'true\',\'TRUE\'))'
elif loan_amount_col:
    loan_indicator = f'b."{loan_amount_col}" IS NOT NULL'
else:
    # try loan provider presence
    loan_provider_col = find(['loan_provider','loanProvider','Loan_Provider'], buyers_cols)
    if loan_provider_col:
        loan_indicator = f'b."{loan_provider_col}" IS NOT NULL'
    else:
        raise RuntimeError("Could not determine loan indicator column in buyers table (loan_taken/loan_amount/loan_provider).")

buyer_id_ref = buyer_id_col or 'ROWID'  # fallback to ROWID if explicit id not present
if buyer_id_col is None:
    buyer_id_ref = 'ROWID'

query = f"""
SELECT
    {city_expr} AS city,
    COUNT(DISTINCT CASE WHEN {loan_indicator} THEN b."{buyer_id_ref}" END) AS buyers_with_loans,
    COUNT(DISTINCT b."{buyer_id_ref}") AS total_buyers,
    ROUND(
        100.0 * COUNT(DISTINCT CASE WHEN {loan_indicator} THEN b."{buyer_id_ref}" END)
        / NULLIF(COUNT(DISTINCT b."{buyer_id_ref}"), 0),
        2
    ) AS loan_uptake_rate
FROM buyers b
{join_clause}
GROUP BY
    {city_expr}
ORDER BY
    loan_uptake_rate DESC;
"""

# rebuild a correct join clause (handles buyers.sale_id -> sales.Listing_ID cases)
join_parts = []
if buyer_sale_id_col:
    if sales_id_col:
        join_parts.append(f'LEFT JOIN sales s ON b."{buyer_sale_id_col}" = s."{sales_id_col}"')
    elif sales_listing_id_col:
        join_parts.append(f'LEFT JOIN sales s ON b."{buyer_sale_id_col}" = s."{sales_listing_id_col}"')
if sales_listing_id_col and listing_id_col:
    join_parts.append(f'LEFT JOIN listings l ON s."{sales_listing_id_col}" = l."{listing_id_col}"')

new_join_clause = "\n".join(join_parts) if join_parts else join_clause

# replace the possibly-broken join_clause in the already-built query
corrected_query = query.replace(join_clause, new_join_clause)

df_loan_uptake_rate = pd.read_sql(corrected_query, conn)
print(df_loan_uptake_rate)

          city  buyers_with_loans  total_buyers  loan_uptake_rate
0  Los Angeles               1811          3552             50.99
1      Chicago               2188          4327             50.57
2     New York               1913          3809             50.22
3      Houston               1809          3639             49.71
4      Phoenix               2313          4673             49.50

Q28 . What is the average loan amount by buyer type?

In [5]:
query = """
SELECT
    buyer_type,
    ROUND(
        AVG(CASE WHEN loan_amount IS NOT NULL THEN loan_amount END),
        2
    ) AS avg_loan_amount,
    SUM(CASE WHEN loan_amount IS NOT NULL THEN 1 ELSE 0 END) AS total_loans
FROM buyers
GROUP BY buyer_type
ORDER BY avg_loan_amount DESC;
"""

df_avg_loan_amount = pd.read_sql(query, conn)
print(df_avg_loan_amount)

  buyer_type  avg_loan_amount  total_loans
0   Investor       2629271.94         9980
1   End User       2599433.82        10020

Q29 . Which payment mode is most commonly used?

In [7]:
# Prefer payments table if it exists, otherwise fall back to buyers.payment_mode
tables = [r[0] for r in conn.execute("SELECT name FROM sqlite_master WHERE type='table'").fetchall()]

if 'payments' in tables:
    query = """
    SELECT
        payment_mode,
        COUNT(payment_id) AS usage_count
    FROM payments
    GROUP BY payment_mode
    ORDER BY usage_count DESC;
    """
else:
    query = """
    SELECT
        payment_mode,
        COUNT(buyer_id) AS usage_count
    FROM buyers
    GROUP BY payment_mode
    ORDER BY usage_count DESC;
    """

df_usage_count = pd.read_sql(query, conn)
print(df_usage_count)

    payment_mode  usage_count
0           Cash         5088
1            UPI         5012
2         Cheque         4951
3  Bank Transfer         4949

Q30 . Do loan-backed purchases take longer to close?

In [2]:
# Use existing connection `conn`. Compute avg days to close for loan-backed vs non-loan purchases
import pandas as pd

# discover columns
def cols(table):
    return [r[1] for r in conn.execute(f"PRAGMA table_info({table})").fetchall()]

buyers_cols = cols("buyers")
sales_cols = cols("sales")
listing_cols = cols("listings")

def find(cands, arr):
    for c in cands:
        if c in arr:
            return c
    return None

# relevant columns
buyer_sale_id_col = find(['sale_id','sales_id','Sale_ID','saleId'], buyers_cols)
loan_taken_col = find(['loan_taken','loanTaken','loan_taken_flag'], buyers_cols)
loan_amount_col = find(['loan_amount','Loan_Amount','loanAmount'], buyers_cols)

sales_id_col = find(['sales_id','sale_id','Sale_ID','id'], sales_cols)
sales_listing_id_col = find(['listing_id','Listing_ID','ListingId'], sales_cols)
sales_date_col = find(['Date_Sold','sale_date','Sale_Date','DateSold','SaleDate'], sales_cols)

listing_id_col = find(['Listing_ID','listing_id','ListingId','listings_id'], listing_cols)
listing_date_col = find(['Date_Listed','listed_date','listedDate','DateListed'], listing_cols)

# determine loan indicator expression
if loan_taken_col:
    loan_indicator = f"(b.\"{loan_taken_col}\" = 1 OR b.\"{loan_taken_col}\" IN ('True','true','TRUE'))"
elif loan_amount_col:
    loan_indicator = f"b.\"{loan_amount_col}\" IS NOT NULL"
else:
    raise RuntimeError("Could not find loan indicator (loan_taken / loan_amount) in buyers table.")

# build joins: buyers -> sales -> listings
joins = []
if buyer_sale_id_col and sales_id_col:
    joins.append(f'JOIN sales s ON b.\"{buyer_sale_id_col}\" = s.\"{sales_id_col}\"')
elif buyer_sale_id_col and sales_listing_id_col:
    joins.append(f'JOIN sales s ON b.\"{buyer_sale_id_col}\" = s.\"{sales_listing_id_col}\"')
elif sales_id_col and sales_listing_id_col:
    joins.append('JOIN sales s ON 1=1')  # will be filtered later if needed
else:
    raise RuntimeError("Could not determine join path between buyers and sales tables.")

if sales_listing_id_col and listing_id_col:
    joins.append(f'JOIN listings l ON s.\"{sales_listing_id_col}\" = l.\"{listing_id_col}\"')
elif listing_date_col and sales_date_col:
    # if listings not joinable, try to compute from sales dates only
    pass
else:
    raise RuntimeError("Could not join sales to listings to get listing/listed date.")

join_clause = "\n".join(joins)

# ensure we have sale and listing date columns for days calculation
if not sales_date_col:
    raise RuntimeError("Could not find sale date column in sales table.")
if not listing_date_col:
    raise RuntimeError("Could not find listing/listed date column in listings table.")

query = f"""
SELECT
    CASE WHEN {loan_indicator} THEN 'Loan-backed' ELSE 'No Loan' END AS financing_type,
    ROUND(AVG(julianday(s."{sales_date_col}") - julianday(l."{listing_date_col}")), 2) AS avg_days_to_close,
    COUNT(*) AS total_deals
FROM buyers b
{join_clause}
WHERE s."{sales_date_col}" IS NOT NULL
  AND l."{listing_date_col}" IS NOT NULL
GROUP BY financing_type
ORDER BY avg_days_to_close DESC;
"""

df_avg_days_to_close = pd.read_sql(query, conn)
print(df_avg_days_to_close)

  financing_type  avg_days_to_close  total_deals
0    Loan-backed              62.15        10034
1        No Loan              61.07         9966

Q27 . Which cities have the highest loan uptake rate?

In [15]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("brickview_realstate.db")
query = """
SELECT
    b.city,
    COUNT(DISTINCT CASE
        WHEN l.loan_status = 'Approved' THEN b.buyer_id
    END) AS buyers_with_loans,
    COUNT(DISTINCT b.buyer_id) AS total_buyers,
    ROUND(
        COUNT(DISTINCT CASE
            WHEN l.loan_status = 'Approved' THEN b.buyer_id
        END) * 100.0 /
        COUNT(DISTINCT b.buyer_id),
        2
    ) AS loan_uptake_rate
FROM buyers b
LEFT JOIN loans l
    ON b.buyer_id = l.buyer_id
GROUP BY b.city
ORDER BY loan_uptake_rate DESC;
"""

df_loan_uptake_by_city = pd.read_sql(corrected_query, conn)
print(df_loan_uptake_by_city)

          city  buyers_with_loans  total_buyers  loan_uptake_rate
0  Los Angeles               1811          3552             50.99
1      Chicago               2188          4327             50.57
2     New York               1913          3809             50.22
3      Houston               1809          3639             49.71
4      Phoenix               2313          4673             49.50